import type { GeneratedProgram, GeneratorInput, ProgramMeta } from './types';
import { generateSmolovJr } from './generators/smolov-jr';
import { generateWendler531 } from './generators/wendler531';
import { generatePPL } from './generators/ppl';
import { generateStrongLifts } from './generators/stronglifts';
import { generateGZCL } from './generators/gzcl';
import { generateNSuns } from './generators/nsuns';
import { generatePHUL } from './generators/phul';
import { generateStartingStrength } from './generators/starting-strength';
import { generateGVT } from './generators/gvt';
import { generateTexasMethod } from './generators/texas-method';
import { generatePHAT } from './generators/phat';

export type GeneratorFn = (input: GeneratorInput) => GeneratedProgram;

export const programRegistry: Record<string, GeneratorFn> = {
  'smolov-jr': generateSmolovJr,
  'wendler-531': generateWendler531,
  'ppl': generatePPL,
  'stronglifts-5x5': generateStrongLifts,
  'gzcl': generateGZCL,
  'nsuns-531': generateNSuns,
  'phul': generatePHUL,
  'starting-strength': generateStartingStrength,
  'gvt': generateGVT,
  'texas-method': generateTexasMethod,
  'phat': generatePHAT,
};

export const programMeta: ProgramMeta[] = [
  {
    slug: 'smolov-jr',
    nameJa: 'Smolov Jr',
    nameEn: 'Smolov Jr',
    seoTitleJa: 'Smolov Jr 計算機｜ベンチプレス・スクワット1RMから全12日程を自動生成',
    seoTitleEn: 'Smolov Jr Calculator — Auto-generate all 12 sessions from your 1RM',
    seoDescJa: '1RMを入力するだけでSmolov Jrの全3週間・12セッションの重量・セット・レップを自動計算。ベンチプレスとスクワットに対応。スプレッドシート不要。',
    seoDescEn: 'Enter your 1RM and get all 12 Smolov Jr sessions — weights, sets, and reps auto-calculated. No spreadsheet needed. Bench press and squat variants included.',
    descJa: '3週間のベンチプレス/スクワット特化プログラム。1RMを大幅に更新できる高強度ピーキング法。',
    descEn: '3-week peaking program for bench press and/or squat. Rapid 1RM gains through high-frequency intensity.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 3,
    intensityRange: '70–85%',
    relatedSlugs: ['wendler-531', 'nsuns-531', 'texas-method'],
    targetAudienceJa: 'トレーニング歴1年以上の上級者で、ベンチプレスまたはスクワットの1RMを3週間で大幅に更新したい方。試合・イベント前のピーキングにも最適。',
    targetAudienceEn: 'Advanced lifters with 1+ year of training experience who want to peak bench press or squat 1RM in 3 weeks. Also ideal for pre-meet or pre-event peaking.',
    faq: [
      {
        questionJa: 'Smolov Jrは何週間のプログラムですか？',
        answerJa: '全3週間（21日）のプログラムです。週4日・全12セッションで構成されます。ピーキング目的のため、終了後は通常プログラムに戻ることを推奨します。',
        questionEn: 'How many weeks is Smolov Jr?',
        answerEn: 'Smolov Jr is a 3-week (21-day) program with 4 training days per week — 12 sessions total. It is a peaking block; return to your regular program after completing it.',
      },
      {
        questionJa: 'Smolov Jrは初心者でも使えますか？',
        answerJa: 'いいえ、上級者向けです。最低でも1年以上のトレーニング歴があり、フォームが完成していることが前提です。初心者はStrongLifts 5×5をお勧めします。',
        questionEn: 'Is Smolov Jr suitable for beginners?',
        answerEn: 'No — it is an advanced program requiring at least one year of consistent training with solid technique. Beginners should start with StrongLifts 5×5 or Starting Strength.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: 'Smolov Jrは3週間の集中ピーキング法で1種目の1RM更新に特化しています。5/3/1は4週サイクルを数ヶ月継続する長期プログラムです。短期間でのPR更新ならSmolov Jr、長期的な筋力向上なら5/3/1が向いています。',
        questionEn: 'What is the difference between Smolov Jr and Wendler 5/3/1?',
        answerEn: 'Smolov Jr is a 3-week peaking block focused on spiking your 1RM on a single lift. Wendler 5/3/1 is a long-term 4-week cycle run for months at a time. Use Smolov Jr for a fast PR attempt; use 5/3/1 for sustained long-term strength gains.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: 'ベンチプレスまたはスクワットの1RMをkg単位で入力し、「プログラムを生成」を押すだけです。全3週間・12セッション分の重量・セット・レップが自動で計算されます。スプレッドシートは不要です。',
        questionEn: 'How do I use this Smolov Jr calculator?',
        answerEn: 'Enter your bench press or squat 1RM in kilograms and press Generate. All 12 sessions across 3 weeks are output with exact weights, sets, and reps. No spreadsheet required.',
      },
    ],
  },
  {
    slug: 'wendler-531',
    nameJa: 'Wendler 5/3/1',
    nameEn: 'Wendler 5/3/1',
    seoTitleJa: '5/3/1 計算機｜Wendler 5/3/1の重量を1RMから自動計算',
    seoTitleEn: '5/3/1 Calculator — Wendler 5/3/1 weights auto-calculated from your 1RM',
    seoDescJa: '1RM入力で5/3/1の4週サイクル全セッションを自動生成。TM・パーセンテージ計算・BBBアクセサリーをまとめて出力。中級者の定番プログラム。',
    seoDescEn: 'Auto-generate the full Wendler 5/3/1 four-week cycle from your 1RM. Training max, percentages, and BBB accessory work all calculated instantly.',
    descJa: '4週サイクルの王道筋力プログラム。BBBボリュームで筋量も同時に伸ばす中級者向けの定番。',
    descEn: 'The classic 4-week strength cycle with BBB accessory work. A proven intermediate program for long-term gains.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 4,
    intensityRange: '65–95%',
    relatedSlugs: ['nsuns-531', 'texas-method', 'gzcl'],
    targetAudienceJa: '線形プログレッションが頭打ちになった中級者。長期的な筋力向上を求めており、週4日でシンプルかつ持続可能なプログラムを望む方。',
    targetAudienceEn: 'Intermediate lifters who have exhausted linear progression and want a sustainable, long-term strength program that fits a 4-day training week.',
    faq: [
      {
        questionJa: 'Wendler 5/3/1は何週間のプログラムですか？',
        answerJa: '1サイクルは4週間です。最終週がディロードになります。通常は複数サイクルを継続して実施し、数ヶ月から数年単位で使えるプログラムです。',
        questionEn: 'How long is the Wendler 5/3/1 program?',
        answerEn: 'One cycle is 4 weeks, with the final week as a deload. The program is designed to be run for multiple cycles — often months or years — with your training max increasing each cycle.',
      },
      {
        questionJa: '5/3/1は初心者でも使えますか？',
        answerJa: '中級者向けです。基本的な種目（スクワット、デッドリフト、ベンチプレス、プレス）のフォームが固まっていることが前提です。完全な初心者にはStrongLifts 5×5かStarting Strengthをお勧めします。',
        questionEn: 'Can beginners do Wendler 5/3/1?',
        answerEn: 'It is aimed at intermediate lifters. You should have solid technique on the four main lifts (squat, deadlift, bench, press). Complete beginners will make faster progress with StrongLifts 5×5 or Starting Strength.',
      },
      {
        questionJa: 'nSuns 5/3/1との違いは何ですか？',
        answerJa: 'nSunsはWendler 5/3/1の高ボリューム派生版です。1種目あたりのセット数が多く（9セット以上）、週5日のトレーニングが必要です。オリジナルの5/3/1はシンプルで週4日、疲労の蓄積が少なく回復しやすいのが特長です。',
        questionEn: 'What is the difference between nSuns 5/3/1 and regular Wendler 5/3/1?',
        answerEn: 'nSuns is a high-volume derivative with 9+ sets per main lift and 5 training days per week. Original Wendler 5/3/1 is simpler, runs 4 days per week, and accumulates less fatigue — making it more sustainable for most lifters.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、4週サイクルの全セッションで使うトレーニングマックス（TM）と各セットの重量が自動計算されます。',
        questionEn: 'How does the 5/3/1 calculator work?',
        answerEn: 'Enter your 1RM for each lift and click Generate. The calculator derives your Training Max (90% of 1RM) and outputs exact working weights for every set across the full 4-week cycle.',
      },
    ],
  },
  {
    slug: 'ppl',
    nameJa: 'PPL（Push/Pull/Legs）',
    nameEn: 'PPL (Push/Pull/Legs)',
    seoTitleJa: 'PPL プログラム作成｜Push/Pull/Legs 6日分割を1RMから自動生成',
    seoTitleEn: 'PPL Program Generator — Build your Push/Pull/Legs split from your 1RM',
    seoDescJa: '1RMからPPLの全6日分・種目・重量・レップを自動生成。ベンチプレス・デッドリフト・スクワットのパーセンテージが即座に計算できます。',
    seoDescEn: 'Generate a complete PPL (Push/Pull/Legs) 6-day split with weights auto-calculated from your 1RM. Bench, deadlift, and squat percentages instantly.',
    descJa: '週6日・Push/Pull/Legsの6分割。筋量と筋力を同時に伸ばしたい中級者に最適。',
    descEn: '6-day Push/Pull/Legs split. Ideal for intermediates looking to build both muscle size and strength.',
    level: 'intermediate',
    daysPerWeek: 6,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–80%',
    relatedSlugs: ['phul', 'phat', 'gvt'],
    targetAudienceJa: '全身プログラムを卒業し筋量と筋力を同時に伸ばしたい中級者。週6日トレーニングできる時間とエネルギーがある方。',
    targetAudienceEn: 'Intermediate lifters who have outgrown full-body routines and want to build muscle and strength simultaneously. Requires 6 training days per week.',
    faq: [
      {
        questionJa: 'PPLは何週間のプログラムですか？',
        answerJa: 'PPLは特定の終了期間がなく継続して回せる分割プログラムです。一般的に8〜12週を1フェーズとして区切り、重量進捗を管理します。週6日トレーニングするため、休養をしっかり確保してください。',
        questionEn: 'How many weeks is the PPL program?',
        answerEn: 'PPL has no fixed end date — it is an ongoing split. Most people run it in 8–12 week phases before resetting or adjusting weights. With 6 training days per week, recovery management is critical.',
      },
      {
        questionJa: 'PPLは初心者でも大丈夫ですか？',
        answerJa: '中級者向けです。線形プログレッションが頭打ちになった時点でPPLに移行するのが理想です。完全な初心者は週3日の全身プログラム（StrongLifts 5×5など）から始めることを推奨します。',
        questionEn: 'Is PPL good for beginners?',
        answerEn: 'PPL is best suited for intermediates who have exhausted linear progression. True beginners are better served by a 3-day full-body routine like StrongLifts 5×5 before transitioning to a 6-day split.',
      },
      {
        questionJa: 'PHULとの違いは何ですか？',
        answerJa: 'PPLは週6日の6分割（プッシュ・プル・レッグス各2回）で筋量を中心に狙います。PHULは週4日でパワー日と肥大日を組み合わせた構成です。トレーニング頻度を優先するならPPL、筋力と筋肥大のバランスを重視するならPHULが適しています。',
        questionEn: 'How does PPL differ from PHUL?',
        answerEn: 'PPL trains 6 days per week hitting each movement pattern twice, prioritizing hypertrophy volume. PHUL runs 4 days per week and combines power days with hypertrophy days. Choose PPL for maximum training frequency; choose PHUL for a balanced strength-and-size approach.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: 'ベンチ・スクワット・デッドリフトの1RMを入力して生成するだけです。Push/Pull/Legsの全6日分の種目・重量・セット・レップが一括で出力されます。',
        questionEn: 'How do I use the PPL generator?',
        answerEn: 'Enter your 1RMs for bench, squat, and deadlift, then generate. You get the full 6-day split — exercises, weights, sets, and reps — all calculated for your strength level.',
      },
    ],
  },
  {
    slug: 'stronglifts-5x5',
    nameJa: 'StrongLifts 5×5',
    nameEn: 'StrongLifts 5×5',
    seoTitleJa: 'StrongLifts 5×5 計算機｜初期重量と週間スケジュールを自動生成',
    seoTitleEn: 'StrongLifts 5×5 Calculator — Starting weights and weekly schedule auto-generated',
    seoDescJa: '1RMから5×5の開始重量とA/Bワークアウトを自動生成。毎セッション何kgを使えばいいかをすぐ確認できます。初心者向け線形プログレッション。',
    seoDescEn: 'Get your 5×5 starting weights and A/B workout schedule from your 1RM. Know exactly what to lift each session. The go-to beginner linear progression.',
    descJa: '週3回・5種目のみ。毎回重量が上がる線形プログレッション。初心者が最速で力をつける方法。',
    descEn: 'Train 3 days/week with just 5 exercises. Linear progression — add weight every session. The fastest way to get strong as a beginner.',
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 12,
    intensityRange: '60–80%',
    relatedSlugs: ['starting-strength', 'texas-method', 'wendler-531'],
    targetAudienceJa: 'バーベルトレーニングを始めたばかりの初心者。週3日・5種目のシンプルさで毎回成長を実感したい方。',
    targetAudienceEn: 'Beginners starting out with barbell training who want a simple, effective program. Only 3 days per week — perfect for building the training habit.',
    faq: [
      {
        questionJa: 'StrongLifts 5×5は何週間のプログラムですか？',
        answerJa: '公式には終了期間の設定はありませんが、一般的に12週（約3ヶ月）が目安です。重量が上がり続ける限り継続できますが、停滞が始まったら中級プログラムへの移行を検討します。',
        questionEn: 'How long is StrongLifts 5×5?',
        answerEn: 'There is no fixed end date, but most lifters progress for around 12 weeks (3 months) before stalls accumulate. Once you hit consistent plateaus, it\'s time to move to an intermediate program like Wendler 5/3/1.',
      },
      {
        questionJa: 'StrongLifts 5×5はどんな人に向いていますか？',
        answerJa: 'バーベルトレーニングを始めたばかりの初心者に最適です。週3日・5種目のみというシンプルさで、毎セッション重量を上げながら確実に筋力がつきます。',
        questionEn: 'Who is StrongLifts 5×5 for?',
        answerEn: 'It is ideal for beginners starting barbell training. The simplicity — 3 days per week, only 5 exercises — makes it easy to build the habit while adding weight every session.',
      },
      {
        questionJa: 'Starting Strengthとの違いは何ですか？',
        answerJa: '両者とも初心者向けの線形プログレッションですが、StrongLiftsはA/B交互のスクワット5×5が中心で、Starting Strengthはスクワット3×5にデッドリフトとパワークリーンが加わります。実用的な手軽さではStrongLiftsが上回る傾向があります。',
        questionEn: 'What is the difference between StrongLifts 5×5 and Starting Strength?',
        answerEn: 'Both are beginner linear progression programs. StrongLifts uses a 5×5 A/B squat-centered split; Starting Strength uses 3×5 with deadlifts and power cleans. Starting Strength has more detailed coaching instructions; StrongLifts is simpler to self-manage.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力するだけで、StrongLifts 5×5の開始重量とA・Bワークアウトの種目・重量が自動生成されます。初回のジムにそのまま持っていける状態になります。',
        questionEn: 'How does the StrongLifts 5×5 calculator work?',
        answerEn: 'Enter your current 1RM estimates and generate. You get your starting weights for Workout A and Workout B — ready to take to the gym on day one.',
      },
    ],
  },
  {
    slug: 'gzcl',
    nameJa: 'GZCL Method',
    nameEn: 'GZCL Method',
    seoTitleJa: 'GZCL プログラム計算機｜T1/T2/T3の重量を1RMから自動計算',
    seoTitleEn: 'GZCL Calculator — T1/T2/T3 weights auto-calculated from your 1RM',
    seoDescJa: '1RMからGZCLのT1・T2・T3全種目の重量を自動計算。スプレッドシートなしで4日間のプログラム全体を即生成。上級者向けストレングス法。',
    seoDescEn: 'Auto-calculate GZCL T1/T2/T3 weights from your 1RM. Generate the full 4-day program instantly without a spreadsheet.',
    descJa: 'T1/T2/T3の3層構造。高重量から高レップまで全域を網羅する上級者向けストレングス法。',
    descEn: 'Three-tier T1/T2/T3 structure covering heavy strength to high-rep work. A comprehensive approach for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '75–95%',
    relatedSlugs: ['wendler-531', 'nsuns-531', 'phat'],
    targetAudienceJa: '自分でプログラムを設計したい上級者。T1/T2/T3の構造を使ってカスタマイズしながら最高レベルの筋力を追求したい方。',
    targetAudienceEn: 'Advanced lifters who want to self-program using a flexible framework. Ideal for those who want to customize volume and intensity across T1/T2/T3 tiers.',
    faq: [
      {
        questionJa: 'GZCLメソッドは何週間のプログラムですか？',
        answerJa: 'GZCLはフレームワークであり、固定の期間はありません。一般的には12週を1ブロックとして計画し、T1・T2・T3の構成を変えながら長期的に継続します。',
        questionEn: 'How long is the GZCL program?',
        answerEn: 'GZCL is a framework rather than a fixed program. Most implementations plan 12-week blocks, cycling T1/T2/T3 exercise selections. It can be run indefinitely with periodic block changes.',
      },
      {
        questionJa: 'GZCLは初心者に向いていますか？',
        answerJa: '上級者向けです。T1/T2/T3の負荷管理と自己プログラミングの知識が必要なため、まずStrongLifts 5×5などで基礎を作ってから挑戦することを推奨します。',
        questionEn: 'Is GZCL for beginners?',
        answerEn: 'GZCL is designed for advanced lifters. Managing T1/T2/T3 load progression requires training experience and program literacy. Build your foundation with a beginner program first.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: '5/3/1はプレスクリプティブで週4日・各メイン種目に1日ずつ当てます。GZCLは柔軟なフレームワークで、T1（最重量・低レップ）をベースに補助種目の量を自由に設計できます。GZCLの方が上級者がカスタマイズできる余地が大きいです。',
        questionEn: 'How does GZCL differ from Wendler 5/3/1?',
        answerEn: '5/3/1 is prescriptive — 4 days per week, one main lift per session. GZCL is a flexible framework where you design T2 and T3 volume around heavy T1 work. GZCL offers more customization for experienced programmers.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '主要種目の1RMを入力すると、T1/T2/T3の各種目の重量が自動計算されます。スプレッドシートなしでGZCLの全4日プログラムを即座に確認できます。',
        questionEn: 'How do I use the GZCL calculator?',
        answerEn: 'Enter your 1RMs and generate — the calculator outputs T1, T2, and T3 weights across the full 4-day program. No spreadsheet needed to run the GZCL method.',
      },
    ],
  },
  {
    slug: 'nsuns-531',
    nameJa: 'nSuns 5/3/1',
    nameEn: 'nSuns 5/3/1',
    seoTitleJa: 'nSuns 計算機｜nSuns 5/3/1の9セット重量を1RMから自動生成',
    seoTitleEn: 'nSuns Calculator — nSuns 5/3/1 weights for all 9 sets, auto-generated from 1RM',
    seoDescJa: '1RMからnSunsの全5日・各セットの重量を自動計算。T1の9セット+AMRAPをスプレッドシートなしで管理。高ボリューム5/3/1を手軽に実行。',
    seoDescEn: 'Auto-generate nSuns 5/3/1 weights for every set across all 5 days from your 1RM. Ditch the spreadsheet — get the full high-volume program instantly.',
    descJa: '5/3/1の高ボリューム派生版。週5日・1種目9セット以上の超高強度プログラム。',
    descEn: 'A high-volume 5/3/1 variant. 5 days/week with 9+ sets per main lift. For those who want maximum volume.',
    level: 'advanced',
    daysPerWeek: 5,
    category: 'strength',
    durationWeeks: 16,
    intensityRange: '70–95%',
    relatedSlugs: ['wendler-531', 'gzcl', 'smolov-jr'],
    targetAudienceJa: '5/3/1の経験があり、さらに高いボリュームに挑戦したい中〜上級者。週5日トレーニングできる十分な回復能力がある方。',
    targetAudienceEn: 'Intermediate-to-advanced lifters experienced with 5/3/1 who want to push volume higher. Requires 5 training days per week and strong recovery.',
    faq: [
      {
        questionJa: 'nSuns 5/3/1は何週間のプログラムですか？',
        answerJa: 'nSunsは16週（4ヶ月）を目安にする高ボリュームプログラムです。ただし固定の終了期間はなく、継続して回すことも可能です。',
        questionEn: 'How long is the nSuns 5/3/1 program?',
        answerEn: 'nSuns is typically run for 16 weeks (about 4 months) as a structured block, but has no mandatory end date. Some lifters run it for much longer with periodic deloads.',
      },
      {
        questionJa: 'nSunsはオリジナルの5/3/1より難しいですか？',
        answerJa: 'はい、大幅にボリュームが多いです。メイン種目1つあたり9セット以上、週5日のトレーニングが必要なため、回復能力が高い中〜上級者向けです。Wendler 5/3/1に慣れた後でnSunsへ移行するのが一般的な流れです。',
        questionEn: 'Is nSuns harder than regular Wendler 5/3/1?',
        answerEn: 'Yes — significantly more volume. nSuns requires 9+ sets per main lift across 5 training days per week. It suits intermediate-to-advanced lifters with good recovery capacity. A common path is to master Wendler 5/3/1 first, then graduate to nSuns.',
      },
      {
        questionJa: 'nSunsに初心者は向いていませんか？',
        answerJa: '向いていません。週5日・高ボリュームのプログラムは初心者には過剰であり、怪我のリスクが高まります。まずStrongLifts 5×5やStarting Strengthで半年〜1年のベースを作ることが重要です。',
        questionEn: 'Can beginners do nSuns?',
        answerEn: 'No. The 5-day high-volume structure is excessive for beginners and raises injury risk. Build a solid base with StrongLifts 5×5 or Starting Strength for 6–12 months before attempting nSuns.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力すると、nSunsの全5日間・各セット（T1の9セット含む）の重量が自動生成されます。AMRAPセットのターゲット重量も出力されます。',
        questionEn: 'How does the nSuns calculator work?',
        answerEn: 'Enter your 1RMs, generate, and get exact weights for every set across all 5 training days — including all 9 T1 sets and the AMRAP target. No spreadsheet required.',
      },
    ],
  },
  {
    slug: 'phul',
    nameJa: 'PHUL',
    nameEn: 'PHUL',
    seoTitleJa: 'PHUL プログラム作成｜パワー&肥大4分割を1RMから自動生成',
    seoTitleEn: 'PHUL Program Generator — Power & Hypertrophy Upper/Lower split from your 1RM',
    seoDescJa: '1RMからPHULの全4日・パワー日と肥大日の重量を自動計算。筋力と筋肥大を同時に狙う週4日分割プログラムを即生成。',
    seoDescEn: 'Build your PHUL (Power Hypertrophy Upper Lower) program from your 1RM. Power and hypertrophy day weights auto-calculated for all 4 days.',
    descJa: 'パワー日＋肥大日の4分割。筋力と筋肥大を最大化するバランスの取れた週4日プログラム。',
    descEn: 'Power + Hypertrophy Upper/Lower split. 4 days/week designed to maximize both strength and muscle size.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
    relatedSlugs: ['phat', 'ppl', 'gvt'],
    targetAudienceJa: '筋力と筋肥大の両方を狙いたい中級者。週4日でパワー日と肥大日を組み合わせたバランスの良いプログラムを求める方。',
    targetAudienceEn: 'Intermediate lifters who want both strength and size gains. PHUL\'s 4-day upper/lower split balances power days and hypertrophy days efficiently.',
    faq: [
      {
        questionJa: 'PHULは何週間のプログラムですか？',
        answerJa: '明確な終了期間はありませんが、一般的に8〜12週を1フェーズとして見直しながら継続します。',
        questionEn: 'How long is the PHUL program?',
        answerEn: 'PHUL does not have a fixed duration. Most lifters run 8–12 week phases, reviewing and adjusting exercise selection at the end of each block.',
      },
      {
        questionJa: 'PHULは初心者に向いていますか？',
        answerJa: '中級者向けです。パワー日（低レップ高重量）と肥大日（中〜高レップ）を使い分けるため、主要種目のフォームが固まっていることが必要です。初心者はまず3日間の全身プログラムから始めましょう。',
        questionEn: 'Is PHUL suitable for beginners?',
        answerEn: 'PHUL is intermediate-level. Cycling between power days (heavy low reps) and hypertrophy days (moderate high reps) requires solid technique on major lifts. Beginners should start with a full-body 3-day program.',
      },
      {
        questionJa: 'PHATとの違いは何ですか？',
        answerJa: 'PHULは週4日の上半身/下半身分割で筋力と筋肥大のバランスを取ります。PHATはLayne Nortonが考案した週5日のプログラムで、より高頻度かつ高ボリュームです。より多くの時間をジムに使えるならPHATが選択肢になります。',
        questionEn: 'How does PHUL differ from PHAT?',
        answerEn: 'PHUL is a 4-day upper/lower split balancing strength and hypertrophy. PHAT (by Layne Norton) is a 5-day program with more frequent power and hypertrophy days. Choose PHAT if you can commit to 5 days per week.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、PHULの全4日（上半身パワー・下半身パワー・上半身肥大・下半身肥大）の種目・重量が一括出力されます。',
        questionEn: 'How do I use the PHUL calculator?',
        answerEn: 'Enter your 1RMs and generate — you get all 4 days (Upper Power, Lower Power, Upper Hypertrophy, Lower Hypertrophy) with exercises and exact weights calculated for your level.',
      },
    ],
  },
  {
    slug: 'starting-strength',
    nameJa: 'Starting Strength',
    nameEn: 'Starting Strength',
    seoTitleJa: 'Starting Strength 計算機｜開始重量とA/Bワークアウトを1RMから生成',
    seoTitleEn: 'Starting Strength Calculator — Starting weights and A/B workouts from your 1RM',
    seoDescJa: '1RMからStarting Strengthの開始重量を自動計算。スクワット・ベンチ・デッドリフト・パワークリーンの初回重量を即座に確認。Rippetoe式初心者プログラム。',
    seoDescEn: 'Get your Starting Strength starting weights from your 1RM. Squat, bench, deadlift, and power clean — know exactly where to begin.',
    descJa: 'Mark Rippetoe考案の初心者向け線形プログレッション。3×5のシンプルさで確実に伸びる。',
    descEn: "Mark Rippetoe's beginner linear progression. Simple 3×5 structure — reliable, proven strength gains.",
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 10,
    intensityRange: '60–80%',
    relatedSlugs: ['stronglifts-5x5', 'texas-method', 'wendler-531'],
    targetAudienceJa: 'バーベルトレーニングを初めて行う完全な初心者。スクワット・デッドリフト・ベンチプレスのフォームを習得しながら確実に力をつけたい方。',
    targetAudienceEn: 'Complete beginners to barbell training. Starting Strength teaches squat, deadlift, bench press, and press technique while building strength through linear progression.',
    faq: [
      {
        questionJa: 'Starting Strengthは何週間のプログラムですか？',
        answerJa: '一般的に10〜16週が目安ですが、線形プログレッションが続く限り延長可能です。週3回・3×5のシンプルな構成で、重量が上がり続けることが唯一の進捗指標です。',
        questionEn: 'How long is Starting Strength?',
        answerEn: 'Typically 10–16 weeks, but you can continue as long as you keep adding weight each session. The 3-day-per-week, 3×5 structure is simple enough to run until linear progression stalls.',
      },
      {
        questionJa: 'Starting StrengthとStrongLifts 5×5はどちらが初心者に向いていますか？',
        answerJa: 'どちらも優れた初心者プログラムです。Starting Strengthは3×5でデッドリフト・パワークリーンを重視し、書籍の指導内容が詳しい。StrongLiftsは5×5でアプリ管理が楽。指導者なしで独学するならStrongLiftsが取り組みやすい傾向があります。',
        questionEn: 'Starting Strength vs StrongLifts 5×5 — which is better for beginners?',
        answerEn: 'Both are excellent. Starting Strength uses 3×5 and emphasizes deadlifts and power cleans with detailed coaching in the book. StrongLifts uses 5×5 and has an easy-to-use app. For self-taught beginners, StrongLifts is often easier to start.',
      },
      {
        questionJa: '女性でもStarting Strengthはできますか？',
        answerJa: 'はい、性別に関係なく有効なプログラムです。開始重量をフォーム習得に適した軽い重量から設定し、毎セッション着実に積み上げていきます。女性でも同じ原理で筋力が伸びます。',
        questionEn: 'Can women do Starting Strength?',
        answerEn: 'Yes, absolutely. Starting Strength is effective regardless of gender. Women start at a manageable weight to learn the movement patterns and progress from there — the linear progression principle works the same way.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '現在の1RMを入力するか、初回の場合はすべて0のまま生成ボタンを押してください。スクワット・ベンチ・デッドリフト・プレスの開始重量とA/Bワークアウトが自動生成されます。',
        questionEn: 'How does the Starting Strength calculator work?',
        answerEn: 'Enter your current 1RMs, or leave them at zero for your very first session. The calculator generates starting weights and your Workout A / Workout B schedule — ready to use on day one.',
      },
    ],
  },
  {
    slug: 'gvt',
    nameJa: 'German Volume Training（GVT）',
    nameEn: 'German Volume Training (GVT)',
    seoTitleJa: 'GVT 計算機｜German Volume Training 10×10の重量を1RMから自動計算',
    seoTitleEn: 'GVT Calculator — German Volume Training 10×10 weights from your 1RM',
    seoDescJa: '1RMからGVT（ジャーマン・ボリューム・トレーニング）の10×10重量を自動計算。6週間・全24セッションの重量を即生成。最大筋肥大を狙う上級者向け。',
    seoDescEn: 'Auto-calculate German Volume Training (GVT) 10×10 weights from your 1RM. Generate the full 6-week, 24-session program instantly.',
    descJa: '10×10の超高ボリューム筋肥大プログラム。6週間で最大の筋量増加を狙う上級者向け。',
    descEn: '10×10 extreme volume hypertrophy program. 6-week cycles designed to maximize muscle growth for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 6,
    intensityRange: '60–70%',
    relatedSlugs: ['ppl', 'phul', 'phat'],
    targetAudienceJa: '筋肥大を最優先とする上級者。高ボリューム刺激で停滞を打ち破りたい、または体型の大きな変化を6週間で求める方。',
    targetAudienceEn: 'Advanced lifters who prioritize maximum hypertrophy. GVT breaks through plateaus with extreme volume and can produce significant size changes in 6 weeks.',
    faq: [
      {
        questionJa: 'GVT（ジャーマン・ボリューム・トレーニング）は何週間ですか？',
        answerJa: '標準的なGVTは6週間です。10×10という極めて高いボリュームで筋肥大を狙います。6週後は休養を挟んでから次のブロックに進むことを推奨します。',
        questionEn: 'How long is German Volume Training (GVT)?',
        answerEn: 'Standard GVT is 6 weeks. The extreme 10×10 volume is designed to maximize hypertrophy in a concentrated block. After 6 weeks, a recovery period is strongly recommended before the next block.',
      },
      {
        questionJa: 'GVTは初心者でも大丈夫ですか？',
        answerJa: '上級者向けです。10×10の超高ボリュームは初心者の回復能力を超えており、怪我やオーバートレーニングのリスクがあります。少なくとも1〜2年のトレーニング歴があることが推奨されます。',
        questionEn: 'Is GVT suitable for beginners?',
        answerEn: 'No — GVT is for advanced lifters. The 10×10 volume exceeds a beginner\'s recovery capacity and carries serious overtraining risk. At minimum 1–2 years of consistent training are recommended.',
      },
      {
        questionJa: 'PPLとGVTはどちらが筋肥大に効果的ですか？',
        answerJa: 'GVTは短期的な筋肥大刺激において非常に強力ですが、6週の集中ブロックです。PPLは週6日の継続的なトレーニングで長期的な筋量増加に適しています。短期集中で体型を変えたいならGVT、持続的な筋量増加ならPPLが向いています。',
        questionEn: 'GVT vs PPL — which is better for hypertrophy?',
        answerEn: 'GVT delivers an intense hypertrophy stimulus in a focused 6-week block. PPL provides sustained hypertrophy volume across 6 days per week for long-term muscle building. Use GVT for a short-term shock block; use PPL for ongoing volume.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '1RMを入力して生成すると、GVTの6週間・全24セッションの10×10重量が自動計算されます。1RMの60〜70%が作業重量の目安です。',
        questionEn: 'How does the GVT calculator work?',
        answerEn: 'Enter your 1RM and generate. The calculator outputs 10×10 working weights for the full 6-week, 24-session program. Working weights are typically set at 60–70% of your 1RM.',
      },
    ],
  },
  {
    slug: 'texas-method',
    nameJa: 'Texas Method',
    nameEn: 'Texas Method',
    seoTitleJa: 'Texas Method 計算機｜Volume/Recovery/Intensity日の重量を1RMから生成',
    seoTitleEn: 'Texas Method Calculator — Volume, Recovery, and Intensity day weights from your 1RM',
    seoDescJa: '1RMからTexas Methodの3日サイクル全種目の重量を自動計算。Volume Day・Recovery Day・Intensity Day（PR日）の重量を一括生成。毎週自己ベストを更新する中級者プログラム。',
    seoDescEn: 'Auto-calculate Texas Method weights for all three days — Volume, Recovery, and Intensity (PR day) — from your 1RM. Set a new PR every week.',
    descJa: '週3日・Volume/Recovery/Intensityの3日サイクル。毎週PRを更新する中級者向け。',
    descEn: '3-day Volume/Recovery/Intensity cycle. Set a new PR every week as an intermediate lifter.',
    level: 'intermediate',
    daysPerWeek: 3,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '70–90%',
    relatedSlugs: ['wendler-531', 'starting-strength', 'stronglifts-5x5'],
    targetAudienceJa: 'StrongLiftsやStarting Strengthを卒業したばかりの中級者。毎週のPR更新を目標に、ボリュームと強度をバランスよく積み上げたい方。',
    targetAudienceEn: 'Intermediate lifters who have graduated from beginner programs and want to set a new PR every week through a structured Volume-Recovery-Intensity cycle.',
    faq: [
      {
        questionJa: 'Texas Methodは何週間のプログラムですか？',
        answerJa: 'Texas Methodは12週を目安にしますが、毎週PRを更新し続ける限り期間の制限はありません。Volume Day・Recovery Day・Intensity Day（PR日）の3日サイクルが続きます。',
        questionEn: 'How long is the Texas Method?',
        answerEn: 'Texas Method has no fixed duration — 12 weeks is a common first block, but the program continues as long as you can hit new PRs on Intensity Day. The 3-day weekly cycle repeats indefinitely.',
      },
      {
        questionJa: 'Texas Methodはどんな人に向いていますか？',
        answerJa: 'StrongLiftsやStarting Strengthを卒業した中級者に最適です。毎週のPRを目標に、Volume DayでボリュームをこなしてIntensity DayでPRに挑む設計です。',
        questionEn: 'Who is the Texas Method for?',
        answerEn: 'Texas Method is ideal for intermediate lifters who have graduated from StrongLifts or Starting Strength. The weekly Volume-Recovery-Intensity cycle allows you to set a new PR every single week.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: 'Texas Methodは週1回のPRを目標にした短期サイクルです。5/3/1は4週サイクルで、最終セットのAMRAPが主な進捗指標です。Texas Methodの方がPR頻度が高く強度重視。5/3/1はボリュームと強度のバランスが取れています。',
        questionEn: 'What is the difference between Texas Method and Wendler 5/3/1?',
        answerEn: 'Texas Method aims for a PR every week using a Volume-Recovery-Intensity 3-day cycle. Wendler 5/3/1 runs 4-week cycles with AMRAPs as the progress marker. Texas Method has a higher PR frequency; 5/3/1 balances volume and intensity across a longer cycle.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力すると、Texas Methodの3日間（ボリューム・回復・インテンシティ）全種目の重量が自動計算されます。Intensity Dayの目標重量もすぐに確認できます。',
        questionEn: 'How do I use the Texas Method calculator?',
        answerEn: 'Enter your 1RMs and generate. The calculator outputs all weights for Volume Day, Recovery Day, and Intensity Day across all main lifts — including your weekly PR target.',
      },
    ],
  },
  {
    slug: 'phat',
    nameJa: 'PHAT',
    nameEn: 'PHAT',
    seoTitleJa: 'PHAT プログラム作成｜Layne Norton式5日分割を1RMから自動生成',
    seoTitleEn: 'PHAT Program Generator — Layne Norton\'s 5-day split from your 1RM',
    seoDescJa: '1RMからPHAT（Power Hypertrophy Adaptive Training）の全5日・パワーデイと肥大デイの重量を自動計算。Layne Norton考案の高頻度プログラムをすぐ実行。',
    seoDescEn: 'Generate Layne Norton\'s PHAT (Power Hypertrophy Adaptive Training) program from your 1RM. Power and hypertrophy day weights auto-calculated across all 5 days.',
    descJa: 'Layne Norton考案の週5日高頻度プログラム。パワーと肥大を両立するアダプティブな設計。',
    descEn: "Layne Norton's 5-day high-frequency program. Adaptive training that bridges powerlifting and bodybuilding.",
    level: 'advanced',
    daysPerWeek: 5,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
    relatedSlugs: ['phul', 'gzcl', 'ppl'],
    targetAudienceJa: 'パワーリフティングとボディビルディングの両方に関心がある上級者。週5日トレーニングでき、筋力と筋量の両立を追求したい方。',
    targetAudienceEn: 'Advanced lifters interested in both powerlifting and bodybuilding. PHAT combines power and hypertrophy training across 5 days per week for dual adaptation.',
    faq: [
      {
        questionJa: 'PHATは何週間のプログラムですか？',
        answerJa: '明確な終了期間はありませんが、8〜12週を1フェーズとして見直しながら継続するのが一般的です。週5日のトレーニングが必要なため、スケジュール管理が重要です。',
        questionEn: 'How long is the PHAT program?',
        answerEn: 'PHAT has no fixed end date. Most lifters run 8–12 week phases, reassessing exercise selection and loads at the end of each block. The 5-day schedule requires good recovery management.',
      },
      {
        questionJa: 'PHATはパワーリフティングとボディビルディングのどちらに向いていますか？',
        answerJa: '両方です。PHATの設計思想はパワー（低レップ高重量）と肥大（中〜高レップ高ボリューム）を同週内で組み合わせることです。Layne Norton自身がパワーリフターとボディビルダーの両面を持つことから生まれたプログラムです。',
        questionEn: 'Is PHAT for powerlifting or bodybuilding?',
        answerEn: 'Both. PHAT bridges powerlifting and bodybuilding by combining power days (low reps, heavy loads) with hypertrophy days (moderate-high reps, high volume) in the same week. It was created by Layne Norton who competes in both disciplines.',
      },
      {
        questionJa: 'PHULとの違いは何ですか？',
        answerJa: 'PHULは週4日、PHATは週5日です。PHATの方がトレーニング頻度が高く、ボリュームも多いため、より高い回復能力が必要です。PHULが忙しいトレーニーに向くのに対し、PHATは週5日ジムに行ける上級者に向いています。',
        questionEn: 'How does PHAT compare to PHUL?',
        answerEn: 'PHUL is 4 days per week; PHAT is 5 days. PHAT has higher frequency and volume, demanding superior recovery. PHUL suits lifters with busy schedules; PHAT is for advanced athletes who can commit to 5 gym days weekly.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、PHATの全5日（パワーデイ2日+肥大デイ3日）の種目と重量が自動出力されます。',
        questionEn: 'How do I use the PHAT calculator?',
        answerEn: 'Enter your 1RMs and generate. The calculator outputs all exercises and weights for the full 5-day PHAT split — 2 power days and 3 hypertrophy days — auto-calculated from your strength levels.',
      },
    ],
  },
];

export function getProgram(slug: string, input: GeneratorInput): GeneratedProgram | null {
  const fn = programRegistry[slug];
  if (!fn) return null;
  return fn(input);
}

export type { ProgramMeta, GeneratedProgram, GeneratorInput };
