import type { GeneratedProgram, GeneratorInput, ProgramMeta } from './types';
import { generateSmolovJr } from './generators/smolov-jr';
import { generateWendler531 } from './generators/wendler531';
import { generatePPL } from './generators/ppl';
import { generateStrongLifts } from './generators/stronglifts';
import { generateGZCL } from './generators/gzcl';
import { generateNSuns } from './generators/nsuns';
import { generatePHUL } from './generators/phul';
import { generateStartingStrength } from './generators/starting-strength';
import { generateGVT } from './generators/gvt';
import { generateTexasMethod } from './generators/texas-method';
import { generatePHAT } from './generators/phat';

export type GeneratorFn = (input: GeneratorInput) => GeneratedProgram;

export const programRegistry: Record<string, GeneratorFn> = {
  'smolov-jr': generateSmolovJr,
  'wendler-531': generateWendler531,
  'ppl': generatePPL,
  'stronglifts-5x5': generateStrongLifts,
  'gzcl': generateGZCL,
  'nsuns-531': generateNSuns,
  'phul': generatePHUL,
  'starting-strength': generateStartingStrength,
  'gvt': generateGVT,
  'texas-method': generateTexasMethod,
  'phat': generatePHAT,
};

export const programMeta: ProgramMeta[] = [
  {
    slug: 'smolov-jr',
    nameJa: 'Smolov Jr',
    nameEn: 'Smolov Jr',
    seoTitleJa: 'Smolov Jr 計算機｜ベンチプレス・スクワット1RMから全12日程を自動生成',
    seoTitleEn: 'Smolov Jr Calculator — Auto-generate all 12 sessions from your 1RM',
    seoDescJa: '1RMを入力するだけでSmolov Jrの全3週間・12セッションの重量・セット・レップを自動計算。ベンチプレスとスクワットに対応。スプレッドシート不要。',
    seoDescEn: 'Enter your 1RM and get all 12 Smolov Jr sessions — weights, sets, and reps auto-calculated. No spreadsheet needed. Bench press and squat variants included.',
    descJa: '3週間のベンチプレス/スクワット特化プログラム。1RMを大幅に更新できる高強度ピーキング法。',
    descEn: '3-week peaking program for bench press and/or squat. Rapid 1RM gains through high-frequency intensity.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 3,
    intensityRange: '70–85%',
  },
  {
    slug: 'wendler-531',
    nameJa: 'Wendler 5/3/1',
    nameEn: 'Wendler 5/3/1',
    seoTitleJa: '5/3/1 計算機｜Wendler 5/3/1の重量を1RMから自動計算',
    seoTitleEn: '5/3/1 Calculator — Wendler 5/3/1 weights auto-calculated from your 1RM',
    seoDescJa: '1RM入力で5/3/1の4週サイクル全セッションを自動生成。TM・パーセンテージ計算・BBBアクセサリーをまとめて出力。中級者の定番プログラム。',
    seoDescEn: 'Auto-generate the full Wendler 5/3/1 four-week cycle from your 1RM. Training max, percentages, and BBB accessory work all calculated instantly.',
    descJa: '4週サイクルの王道筋力プログラム。BBBボリュームで筋量も同時に伸ばす中級者向けの定番。',
    descEn: 'The classic 4-week strength cycle with BBB accessory work. A proven intermediate program for long-term gains.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 4,
    intensityRange: '65–95%',
  },
  {
    slug: 'ppl',
    nameJa: 'PPL（Push/Pull/Legs）',
    nameEn: 'PPL (Push/Pull/Legs)',
    seoTitleJa: 'PPL プログラム作成｜Push/Pull/Legs 6日分割を1RMから自動生成',
    seoTitleEn: 'PPL Program Generator — Build your Push/Pull/Legs split from your 1RM',
    seoDescJa: '1RMからPPLの全6日分・種目・重量・レップを自動生成。ベンチプレス・デッドリフト・スクワットのパーセンテージが即座に計算できます。',
    seoDescEn: 'Generate a complete PPL (Push/Pull/Legs) 6-day split with weights auto-calculated from your 1RM. Bench, deadlift, and squat percentages instantly.',
    descJa: '週6日・Push/Pull/Legsの6分割。筋量と筋力を同時に伸ばしたい中級者に最適。',
    descEn: '6-day Push/Pull/Legs split. Ideal for intermediates looking to build both muscle size and strength.',
    level: 'intermediate',
    daysPerWeek: 6,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–80%',
  },
  {
    slug: 'stronglifts-5x5',
    nameJa: 'StrongLifts 5×5',
    nameEn: 'StrongLifts 5×5',
    seoTitleJa: 'StrongLifts 5×5 計算機｜初期重量と週間スケジュールを自動生成',
    seoTitleEn: 'StrongLifts 5×5 Calculator — Starting weights and weekly schedule auto-generated',
    seoDescJa: '1RMから5×5の開始重量とA/Bワークアウトを自動生成。毎セッション何kgを使えばいいかをすぐ確認できます。初心者向け線形プログレッション。',
    seoDescEn: 'Get your 5×5 starting weights and A/B workout schedule from your 1RM. Know exactly what to lift each session. The go-to beginner linear progression.',
    descJa: '週3回・5種目のみ。毎回重量が上がる線形プログレッション。初心者が最速で力をつける方法。',
    descEn: 'Train 3 days/week with just 5 exercises. Linear progression — add weight every session. The fastest way to get strong as a beginner.',
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 12,
    intensityRange: '60–80%',
  },
  {
    slug: 'gzcl',
    nameJa: 'GZCL Method',
    nameEn: 'GZCL Method',
    seoTitleJa: 'GZCL プログラム計算機｜T1/T2/T3の重量を1RMから自動計算',
    seoTitleEn: 'GZCL Calculator — T1/T2/T3 weights auto-calculated from your 1RM',
    seoDescJa: '1RMからGZCLのT1・T2・T3全種目の重量を自動計算。スプレッドシートなしで4日間のプログラム全体を即生成。上級者向けストレングス法。',
    seoDescEn: 'Auto-calculate GZCL T1/T2/T3 weights from your 1RM. Generate the full 4-day program instantly without a spreadsheet.',
    descJa: 'T1/T2/T3の3層構造。高重量から高レップまで全域を網羅する上級者向けストレングス法。',
    descEn: 'Three-tier T1/T2/T3 structure covering heavy strength to high-rep work. A comprehensive approach for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '75–95%',
  },
  {
    slug: 'nsuns-531',
    nameJa: 'nSuns 5/3/1',
    nameEn: 'nSuns 5/3/1',
    seoTitleJa: 'nSuns 計算機｜nSuns 5/3/1の9セット重量を1RMから自動生成',
    seoTitleEn: 'nSuns Calculator — nSuns 5/3/1 weights for all 9 sets, auto-generated from 1RM',
    seoDescJa: '1RMからnSunsの全5日・各セットの重量を自動計算。T1の9セット+AMRAPをスプレッドシートなしで管理。高ボリューム5/3/1を手軽に実行。',
    seoDescEn: 'Auto-generate nSuns 5/3/1 weights for every set across all 5 days from your 1RM. Ditch the spreadsheet — get the full high-volume program instantly.',
    descJa: '5/3/1の高ボリューム派生版。週5日・1種目9セット以上の超高強度プログラム。',
    descEn: 'A high-volume 5/3/1 variant. 5 days/week with 9+ sets per main lift. For those who want maximum volume.',
    level: 'advanced',
    daysPerWeek: 5,
    category: 'strength',
    durationWeeks: 16,
    intensityRange: '70–95%',
  },
  {
    slug: 'phul',
    nameJa: 'PHUL',
    nameEn: 'PHUL',
    seoTitleJa: 'PHUL プログラム作成｜パワー&肥大4分割を1RMから自動生成',
    seoTitleEn: 'PHUL Program Generator — Power & Hypertrophy Upper/Lower split from your 1RM',
    seoDescJa: '1RMからPHULの全4日・パワー日と肥大日の重量を自動計算。筋力と筋肥大を同時に狙う週4日分割プログラムを即生成。',
    seoDescEn: 'Build your PHUL (Power Hypertrophy Upper Lower) program from your 1RM. Power and hypertrophy day weights auto-calculated for all 4 days.',
    descJa: 'パワー日＋肥大日の4分割。筋力と筋肥大を最大化するバランスの取れた週4日プログラム。',
    descEn: 'Power + Hypertrophy Upper/Lower split. 4 days/week designed to maximize both strength and muscle size.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
  },
  {
    slug: 'starting-strength',
    nameJa: 'Starting Strength',
    nameEn: 'Starting Strength',
    seoTitleJa: 'Starting Strength 計算機｜開始重量とA/Bワークアウトを1RMから生成',
    seoTitleEn: 'Starting Strength Calculator — Starting weights and A/B workouts from your 1RM',
    seoDescJa: '1RMからStarting Strengthの開始重量を自動計算。スクワット・ベンチ・デッドリフト・パワークリーンの初回重量を即座に確認。Rippetoe式初心者プログラム。',
    seoDescEn: 'Get your Starting Strength starting weights from your 1RM. Squat, bench, deadlift, and power clean — know exactly where to begin.',
    descJa: 'Mark Rippetoe考案の初心者向け線形プログレッション。3×5のシンプルさで確実に伸びる。',
    descEn: "Mark Rippetoe's beginner linear progression. Simple 3×5 structure — reliable, proven strength gains.",
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 10,
    intensityRange: '60–80%',
  },
  {
    slug: 'gvt',
    nameJa: 'German Volume Training（GVT）',
    nameEn: 'German Volume Training (GVT)',
    seoTitleJa: 'GVT 計算機｜German Volume Training 10×10の重量を1RMから自動計算',
    seoTitleEn: 'GVT Calculator — German Volume Training 10×10 weights from your 1RM',
    seoDescJa: '1RMからGVT（ジャーマン・ボリューム・トレーニング）の10×10重量を自動計算。6週間・全24セッションの重量を即生成。最大筋肥大を狙う上級者向け。',
    seoDescEn: 'Auto-calculate German Volume Training (GVT) 10×10 weights from your 1RM. Generate the full 6-week, 24-session program instantly.',
    descJa: '10×10の超高ボリューム筋肥大プログラム。6週間で最大の筋量増加を狙う上級者向け。',
    descEn: '10×10 extreme volume hypertrophy program. 6-week cycles designed to maximize muscle growth for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 6,
    intensityRange: '60–70%',
  },
  {
    slug: 'texas-method',
    nameJa: 'Texas Method',
    nameEn: 'Texas Method',
    seoTitleJa: 'Texas Method 計算機｜Volume/Recovery/Intensity日の重量を1RMから生成',
    seoTitleEn: 'Texas Method Calculator — Volume, Recovery, and Intensity day weights from your 1RM',
    seoDescJa: '1RMからTexas Methodの3日サイクル全種目の重量を自動計算。Volume Day・Recovery Day・Intensity Day（PR日）の重量を一括生成。毎週自己ベストを更新する中級者プログラム。',
    seoDescEn: 'Auto-calculate Texas Method weights for all three days — Volume, Recovery, and Intensity (PR day) — from your 1RM. Set a new PR every week.',
    descJa: '週3日・Volume/Recovery/Intensityの3日サイクル。毎週PRを更新する中級者向け。',
    descEn: '3-day Volume/Recovery/Intensity cycle. Set a new PR every week as an intermediate lifter.',
    level: 'intermediate',
    daysPerWeek: 3,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '70–90%',
  },
  {
    slug: 'phat',
    nameJa: 'PHAT',
    nameEn: 'PHAT',
    seoTitleJa: 'PHAT プログラム作成｜Layne Norton式5日分割を1RMから自動生成',
    seoTitleEn: 'PHAT Program Generator — Layne Norton\'s 5-day split from your 1RM',
    seoDescJa: '1RMからPHAT（Power Hypertrophy Adaptive Training）の全5日・パワーデイと肥大デイの重量を自動計算。Layne Norton考案の高頻度プログラムをすぐ実行。',
    seoDescEn: 'Generate Layne Norton\'s PHAT (Power Hypertrophy Adaptive Training) program from your 1RM. Power and hypertrophy day weights auto-calculated across all 5 days.',
    descJa: 'Layne Norton考案の週5日高頻度プログラム。パワーと肥大を両立するアダプティブな設計。',
    descEn: "Layne Norton's 5-day high-frequency program. Adaptive training that bridges powerlifting and bodybuilding.",
    level: 'advanced',
    daysPerWeek: 5,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
  },
];

export function getProgram(slug: string, input: GeneratorInput): GeneratedProgram | null {
  const fn = programRegistry[slug];
  if (!fn) return null;
  return fn(input);
}

export type { ProgramMeta, GeneratedProgram, GeneratorInput };
