import type { GeneratedProgram, GeneratorInput, ProgramMeta } from './types';
import { generateSmolovJr } from './generators/smolov-jr';
import { generateWendler531 } from './generators/wendler531';
import { generatePPL } from './generators/ppl';
import { generateStrongLifts } from './generators/stronglifts';
import { generateGZCL } from './generators/gzcl';
import { generateNSuns } from './generators/nsuns';
import { generatePHUL } from './generators/phul';
import { generateStartingStrength } from './generators/starting-strength';
import { generateGVT } from './generators/gvt';
import { generateTexasMethod } from './generators/texas-method';
import { generatePHAT } from './generators/phat';

export type GeneratorFn = (input: GeneratorInput) => GeneratedProgram;

export const programRegistry: Record<string, GeneratorFn> = {
  'smolov-jr': generateSmolovJr,
  'wendler-531': generateWendler531,
  'ppl': generatePPL,
  'stronglifts-5x5': generateStrongLifts,
  'gzcl': generateGZCL,
  'nsuns-531': generateNSuns,
  'phul': generatePHUL,
  'starting-strength': generateStartingStrength,
  'gvt': generateGVT,
  'texas-method': generateTexasMethod,
  'phat': generatePHAT,
};

export const programMeta: ProgramMeta[] = [
  {
    slug: 'smolov-jr',
    nameJa: 'Smolov Jr',
    nameEn: 'Smolov Jr',
    seoTitleJa: 'Smolov Jr 計算ツール｜ベンチプレス・スクワット1RMから全12日程を自動生成',
    seoTitleEn: 'Smolov Jr Calculator — Auto-generate all 12 sessions from your 1RM',
    seoDescJa: '1RMを入力するだけでSmolov Jrの全3週間・12セッションの重量・セット・レップを自動計算。ベンチプレスとスクワットに対応。スプレッドシート不要。',
    seoDescEn: 'Enter your 1RM and get all 12 Smolov Jr sessions — weights, sets, and reps auto-calculated. No spreadsheet needed. Bench press and squat variants included.',
    descJa: '3週間のベンチプレス/スクワット特化プログラム。1RMを大幅に更新できる高強度ピーキング法。',
    descEn: '3-week peaking program for bench press and/or squat. Rapid 1RM gains through high-frequency intensity.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 3,
    intensityRange: '70–85%',
    relatedSlugs: ['wendler-531', 'nsuns-531', 'texas-method'],
    targetAudienceJa: 'トレーニング歴1年以上の上級者で、ベンチプレスまたはスクワットの1RMを3週間で大幅に更新したい方。試合・イベント前のピーキングにも最適。',
    targetAudienceEn: 'Advanced lifters with 1+ year of training experience who want to peak bench press or squat 1RM in 3 weeks. Also ideal for pre-meet or pre-event peaking.',
    faq: [
      {
        questionJa: 'Smolov Jrは何週間のプログラムですか？',
        answerJa: '全3週間（21日）のプログラムです。週4日・全12セッションで構成されます。ピーキング目的のため、終了後は通常プログラムに戻ることを推奨します。',
        questionEn: 'How many weeks is Smolov Jr?',
        answerEn: 'Smolov Jr is a 3-week (21-day) program with 4 training days per week — 12 sessions total. It is a peaking block; return to your regular program after completing it.',
      },
      {
        questionJa: 'Smolov Jrは初心者でも使えますか？',
        answerJa: 'いいえ、上級者向けです。最低でも1年以上のトレーニング歴があり、フォームが完成していることが前提です。初心者はStrongLifts 5×5をお勧めします。',
        questionEn: 'Is Smolov Jr suitable for beginners?',
        answerEn: 'No — it is an advanced program requiring at least one year of consistent training with solid technique. Beginners should start with StrongLifts 5×5 or Starting Strength.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: 'Smolov Jrは3週間の集中ピーキング法で1種目の1RM更新に特化しています。5/3/1は4週サイクルを数ヶ月継続する長期プログラムです。短期間でのPR更新ならSmolov Jr、長期的な筋力向上なら5/3/1が向いています。',
        questionEn: 'What is the difference between Smolov Jr and Wendler 5/3/1?',
        answerEn: 'Smolov Jr is a 3-week peaking block focused on spiking your 1RM on a single lift. Wendler 5/3/1 is a long-term 4-week cycle run for months at a time. Use Smolov Jr for a fast PR attempt; use 5/3/1 for sustained long-term strength gains.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: 'ベンチプレスまたはスクワットの1RMをkg単位で入力し、「プログラムを生成」を押すだけです。全3週間・12セッション分の重量・セット・レップが自動で計算されます。スプレッドシートは不要です。',
        questionEn: 'How do I use this Smolov Jr calculator?',
        answerEn: 'Enter your bench press or squat 1RM in kilograms and press Generate. All 12 sessions across 3 weeks are output with exact weights, sets, and reps. No spreadsheet required.',
      },
      {
        questionJa: 'Smolov Jrで1RMはどれくらい伸びますか？',
        answerJa: '適切に実施した場合、3週間で1RMが5〜15kg向上することが多く報告されています。増加量は個人差があり、初中級者のほうが大きく伸びる傾向があります。プログラム終了後は1〜2日の軽い回復期間を設けてから新しい1RMをテストしましょう。',
        questionEn: 'How much will my 1RM increase on Smolov Jr?',
        answerEn: 'Lifters commonly report 1RM increases of 5–15 kg over the 3-week block. Gains vary by individual — intermediates and those who have not recently peaked tend to see the largest jumps. After the program, allow 1–2 easy days before testing your new max.',
      },
      {
        questionJa: 'Smolov Jrを終えた後は何をすべきですか？',
        answerJa: 'Smolov Jr終了後は1週間程度の回復期間を取り、その後1RMテストを行うのが一般的です。テスト後はWendler 5/3/1やnSunsなどの長期プログラムに移行し、新しい1RMをベースに継続的な筋力向上を図りましょう。',
        questionEn: 'What should I do after finishing Smolov Jr?',
        answerEn: 'After Smolov Jr, take about one week of lighter training before testing your new 1RM. Once you have your new max, move into a long-term program like Wendler 5/3/1 or nSuns to build on your peak strength.',
      },
    ],
  },
  {
    slug: 'wendler-531',
    nameJa: 'Wendler 5/3/1',
    nameEn: 'Wendler 5/3/1',
    seoTitleJa: '5/3/1 計算ツール｜Wendler 5/3/1の重量を1RMから自動計算',
    seoTitleEn: '5/3/1 Calculator — Wendler 5/3/1 weights auto-calculated from your 1RM',
    seoDescJa: '1RM入力で5/3/1の4週サイクル全セッションを自動生成。TM・パーセンテージ計算・BBBアクセサリーをまとめて出力。中級者の定番プログラム。',
    seoDescEn: 'Auto-generate the full Wendler 5/3/1 four-week cycle from your 1RM. Training max, percentages, and BBB accessory work all calculated instantly.',
    descJa: '4週サイクルの王道筋力プログラム。BBBボリュームで筋量も同時に伸ばす中級者向けの定番。',
    descEn: 'The classic 4-week strength cycle with BBB accessory work. A proven intermediate program for long-term gains.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 4,
    intensityRange: '65–95%',
    relatedSlugs: ['nsuns-531', 'texas-method', 'gzcl'],
    targetAudienceJa: '線形プログレッションが頭打ちになった中級者。長期的な筋力向上を求めており、週4日でシンプルかつ持続可能なプログラムを望む方。',
    targetAudienceEn: 'Intermediate lifters who have exhausted linear progression and want a sustainable, long-term strength program that fits a 4-day training week.',
    faq: [
      {
        questionJa: 'Wendler 5/3/1は何週間のプログラムですか？',
        answerJa: '1サイクルは4週間です。最終週がディロードになります。通常は複数サイクルを継続して実施し、数ヶ月から数年単位で使えるプログラムです。',
        questionEn: 'How long is the Wendler 5/3/1 program?',
        answerEn: 'One cycle is 4 weeks, with the final week as a deload. The program is designed to be run for multiple cycles — often months or years — with your training max increasing each cycle.',
      },
      {
        questionJa: '5/3/1は初心者でも使えますか？',
        answerJa: '中級者向けです。基本的な種目（スクワット、デッドリフト、ベンチプレス、プレス）のフォームが固まっていることが前提です。完全な初心者にはStrongLifts 5×5かStarting Strengthをお勧めします。',
        questionEn: 'Can beginners do Wendler 5/3/1?',
        answerEn: 'It is aimed at intermediate lifters. You should have solid technique on the four main lifts (squat, deadlift, bench, press). Complete beginners will make faster progress with StrongLifts 5×5 or Starting Strength.',
      },
      {
        questionJa: 'nSuns 5/3/1との違いは何ですか？',
        answerJa: 'nSunsはWendler 5/3/1の高ボリューム派生版です。1種目あたりのセット数が多く（9セット以上）、週5日のトレーニングが必要です。オリジナルの5/3/1はシンプルで週4日、疲労の蓄積が少なく回復しやすいのが特長です。',
        questionEn: 'What is the difference between nSuns 5/3/1 and regular Wendler 5/3/1?',
        answerEn: 'nSuns is a high-volume derivative with 9+ sets per main lift and 5 training days per week. Original Wendler 5/3/1 is simpler, runs 4 days per week, and accumulates less fatigue — making it more sustainable for most lifters.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、4週サイクルの全セッションで使うトレーニングマックス（TM）と各セットの重量が自動計算されます。',
        questionEn: 'How does the 5/3/1 calculator work?',
        answerEn: 'Enter your 1RM for each lift and click Generate. The calculator derives your Training Max (90% of 1RM) and outputs exact working weights for every set across the full 4-week cycle.',
      },
      {
        questionJa: 'トレーニングマックス（TM）はどう設定しますか？',
        answerJa: 'Wendler 5/3/1のトレーニングマックス（TM）は実際の1RMの90%に設定します。この計算ツールに1RMを入力すると自動でTMが算出され、各週の作業重量が計算されます。Jim Wendler本人は「最初は控えめなTMから始める」ことを強く推奨しており、慣れてきたら毎サイクル後に上半身+2.5kg・下半身+5kgずつTMを増加させます。',
        questionEn: 'How do I set my Training Max (TM) for Wendler 5/3/1?',
        answerEn: 'Your Training Max is set at 90% of your actual 1RM — this calculator handles that automatically. Wendler strongly recommends starting conservative; a TM that feels "too light" early on pays dividends later. After each 4-week cycle, increase your TM by 2.5 kg for upper body lifts and 5 kg for lower body.',
      },
      {
        questionJa: '5/3/1は何サイクル継続すればいいですか？',
        answerJa: 'Wendler 5/3/1は長期プログラムです。最低でも3〜4サイクル（12〜16週）は継続し、毎サイクル終了後にTMを少しずつ上げていくことで数ヶ月〜数年単位で筋力を伸ばせます。「Boring But Big（BBB）」など補助テンプレートを組み合わせることでマンネリを防ぎながら長期継続できます。',
        questionEn: 'How many cycles of Wendler 5/3/1 should I run?',
        answerEn: 'Plan for at least 3–4 cycles (12–16 weeks) to start, but 5/3/1 is designed to run for years. Small TM increases each cycle compound into substantial strength gains over time. Changing assistance templates (BBB, FSL, etc.) every few cycles keeps training fresh without abandoning the core program.',
      },
    ],
  },
  {
    slug: 'ppl',
    nameJa: 'PPL（Push/Pull/Legs）',
    nameEn: 'PPL (Push/Pull/Legs)',
    seoTitleJa: 'PPL プログラム作成｜Push/Pull/Legs 6日分割を1RMから自動生成',
    seoTitleEn: 'PPL Program Generator — Build your Push/Pull/Legs split from your 1RM',
    seoDescJa: '1RMからPPLの全6日分・種目・重量・レップを自動生成。ベンチプレス・デッドリフト・スクワットのパーセンテージが即座に計算できます。',
    seoDescEn: 'Generate a complete PPL (Push/Pull/Legs) 6-day split with weights auto-calculated from your 1RM. Bench, deadlift, and squat percentages instantly.',
    descJa: '週6日・Push/Pull/Legsの6分割。筋量と筋力を同時に伸ばしたい中級者に最適。',
    descEn: '6-day Push/Pull/Legs split. Ideal for intermediates looking to build both muscle size and strength.',
    level: 'intermediate',
    daysPerWeek: 6,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–80%',
    relatedSlugs: ['phul', 'phat', 'gvt'],
    targetAudienceJa: '全身プログラムを卒業し筋量と筋力を同時に伸ばしたい中級者。週6日トレーニングできる時間とエネルギーがある方。',
    targetAudienceEn: 'Intermediate lifters who have outgrown full-body routines and want to build muscle and strength simultaneously. Requires 6 training days per week.',
    faq: [
      {
        questionJa: 'PPLは何週間のプログラムですか？',
        answerJa: 'PPLは特定の終了期間がなく継続して回せる分割プログラムです。一般的に8〜12週を1フェーズとして区切り、重量進捗を管理します。週6日トレーニングするため、休養をしっかり確保してください。',
        questionEn: 'How many weeks is the PPL program?',
        answerEn: 'PPL has no fixed end date — it is an ongoing split. Most people run it in 8–12 week phases before resetting or adjusting weights. With 6 training days per week, recovery management is critical.',
      },
      {
        questionJa: 'PPLは初心者でも大丈夫ですか？',
        answerJa: '中級者向けです。線形プログレッションが頭打ちになった時点でPPLに移行するのが理想です。完全な初心者は週3日の全身プログラム（StrongLifts 5×5など）から始めることを推奨します。',
        questionEn: 'Is PPL good for beginners?',
        answerEn: 'PPL is best suited for intermediates who have exhausted linear progression. True beginners are better served by a 3-day full-body routine like StrongLifts 5×5 before transitioning to a 6-day split.',
      },
      {
        questionJa: 'PHULとの違いは何ですか？',
        answerJa: 'PPLは週6日の6分割（プッシュ・プル・レッグス各2回）で筋量を中心に狙います。PHULは週4日でパワー日と肥大日を組み合わせた構成です。トレーニング頻度を優先するならPPL、筋力と筋肥大のバランスを重視するならPHULが適しています。',
        questionEn: 'How does PPL differ from PHUL?',
        answerEn: 'PPL trains 6 days per week hitting each movement pattern twice, prioritizing hypertrophy volume. PHUL runs 4 days per week and combines power days with hypertrophy days. Choose PPL for maximum training frequency; choose PHUL for a balanced strength-and-size approach.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: 'ベンチ・スクワット・デッドリフトの1RMを入力して生成するだけです。Push/Pull/Legsの全6日分の種目・重量・セット・レップが一括で出力されます。',
        questionEn: 'How do I use the PPL generator?',
        answerEn: 'Enter your 1RMs for bench, squat, and deadlift, then generate. You get the full 6-day split — exercises, weights, sets, and reps — all calculated for your strength level.',
      },
      {
        questionJa: 'PPLプログラムの休息日はいつ入れますか？',
        answerJa: '標準的なPPLは週6日トレーニングです。Push・Pull・Legsの3日を続けた後に1日休み、またPush・Pull・Legsを繰り返すのが最も一般的なパターンです。疲労や関節の違和感がある場合は柔軟に休息日を追加してください。回復もトレーニングと同じくらい重要です。',
        questionEn: 'When do I take rest days in the PPL program?',
        answerEn: 'Standard PPL runs 6 days per week with one rest day — typically after the first Push/Pull/Legs block before repeating. If fatigue or joint soreness builds, add an extra rest day rather than pushing through. At 6 days per week, recovery quality directly determines whether you can sustain the program long-term.',
      },
      {
        questionJa: 'PPLとPHULはどちらが筋肥大に向いていますか？',
        answerJa: '純粋に筋肥大を目的にするならPPLが有利です。週6日・各筋群への週2回刺激と高ボリュームが特徴です。PHULは週4日でパワー日と肥大日を組み合わせ、筋力と筋量のバランスを追求する設計です。通えるジムの頻度と回復能力に合わせて選択してください。',
        questionEn: 'PPL vs PHUL — which is better for muscle growth?',
        answerEn: 'For pure hypertrophy, PPL has the edge due to higher weekly frequency (6 days) and greater total volume per muscle group. PHUL runs 4 days per week and balances power work with hypertrophy days. Choose PPL if maximizing muscle volume is the goal and you can handle 6 sessions per week; choose PHUL for a balanced strength-and-size program with fewer gym days.',
      },
    ],
  },
  {
    slug: 'stronglifts-5x5',
    nameJa: 'StrongLifts 5×5',
    nameEn: 'StrongLifts 5×5',
    seoTitleJa: 'StrongLifts 5×5 計算ツール｜初期重量と週間スケジュールを自動生成',
    seoTitleEn: 'StrongLifts 5×5 Calculator — Starting weights and weekly schedule auto-generated',
    seoDescJa: '1RMから5×5の開始重量とA/Bワークアウトを自動生成。毎セッション何kgを使えばいいかをすぐ確認できます。初心者向け線形プログレッション。',
    seoDescEn: 'Get your 5×5 starting weights and A/B workout schedule from your 1RM. Know exactly what to lift each session. The go-to beginner linear progression.',
    descJa: '週3回・5種目のみ。毎回重量が上がる線形プログレッション。初心者が最速で力をつける方法。',
    descEn: 'Train 3 days/week with just 5 exercises. Linear progression — add weight every session. The fastest way to get strong as a beginner.',
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 12,
    intensityRange: '60–80%',
    relatedSlugs: ['starting-strength', 'texas-method', 'wendler-531'],
    targetAudienceJa: 'バーベルトレーニングを始めたばかりの初心者。週3日・5種目のシンプルさで毎回成長を実感したい方。',
    targetAudienceEn: 'Beginners starting out with barbell training who want a simple, effective program. Only 3 days per week — perfect for building the training habit.',
    faq: [
      {
        questionJa: 'StrongLifts 5×5は何週間のプログラムですか？',
        answerJa: '公式には終了期間の設定はありませんが、一般的に12週（約3ヶ月）が目安です。重量が上がり続ける限り継続できますが、停滞が始まったら中級プログラムへの移行を検討します。',
        questionEn: 'How long is StrongLifts 5×5?',
        answerEn: 'There is no fixed end date, but most lifters progress for around 12 weeks (3 months) before stalls accumulate. Once you hit consistent plateaus, it\'s time to move to an intermediate program like Wendler 5/3/1.',
      },
      {
        questionJa: 'StrongLifts 5×5はどんな人に向いていますか？',
        answerJa: 'バーベルトレーニングを始めたばかりの初心者に最適です。週3日・5種目のみというシンプルさで、毎セッション重量を上げながら確実に筋力がつきます。',
        questionEn: 'Who is StrongLifts 5×5 for?',
        answerEn: 'It is ideal for beginners starting barbell training. The simplicity — 3 days per week, only 5 exercises — makes it easy to build the habit while adding weight every session.',
      },
      {
        questionJa: 'Starting Strengthとの違いは何ですか？',
        answerJa: '両者とも初心者向けの線形プログレッションですが、StrongLiftsはA/B交互のスクワット5×5が中心で、Starting Strengthはスクワット3×5にデッドリフトとパワークリーンが加わります。実用的な手軽さではStrongLiftsが上回る傾向があります。',
        questionEn: 'What is the difference between StrongLifts 5×5 and Starting Strength?',
        answerEn: 'Both are beginner linear progression programs. StrongLifts uses a 5×5 A/B squat-centered split; Starting Strength uses 3×5 with deadlifts and power cleans. Starting Strength has more detailed coaching instructions; StrongLifts is simpler to self-manage.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力するだけで、StrongLifts 5×5の開始重量とA・Bワークアウトの種目・重量が自動生成されます。初回のジムにそのまま持っていける状態になります。',
        questionEn: 'How does the StrongLifts 5×5 calculator work?',
        answerEn: 'Enter your current 1RM estimates and generate. You get your starting weights for Workout A and Workout B — ready to take to the gym on day one.',
      },
      {
        questionJa: 'StrongLifts 5×5で停滞したらどうすればいいですか？',
        answerJa: '同じ重量で3回連続セットを失敗した場合、10%重量を落としてリセットし、そこから2.5kgずつ積み上げていきます。最も多く使うスクワットが最初に停滞しやすいです。デロードを経て戻ってくると、多くの場合以前の記録を超えられます。',
        questionEn: 'What should I do when I stall on StrongLifts 5×5?',
        answerEn: 'If you fail to complete all 5×5 at the same weight for three sessions in a row, deload by 10% and work back up adding 2.5 kg per session. The squat — trained every session — is usually the first to stall. Deloads are a normal, productive part of the program; most lifters surpass their previous best after resetting.',
      },
      {
        questionJa: 'StrongLifts 5×5の後はどのプログラムに移行すべきですか？',
        answerJa: '線形プログレッションが繰り返し停滞したら中級者プログラムへの移行時期です。Wendler 5/3/1やTexas Methodが代表的な次のステップで、週・月単位のより長いプログレッションサイクルで筋力を伸ばし続けられます。StrongLiftsを6〜12ヶ月継続した後に移行するトレーニーが多いです。',
        questionEn: 'What program should I move to after StrongLifts 5×5?',
        answerEn: 'When linear progression consistently stalls, it\'s time to graduate to an intermediate program. Wendler 5/3/1 and Texas Method are the most common next steps — both extend progression to weekly or monthly cycles. Most lifters make the switch after 6–12 months on StrongLifts having built a solid strength base.',
      },
    ],
  },
  {
    slug: 'gzcl',
    nameJa: 'GZCL Method',
    nameEn: 'GZCL Method',
    seoTitleJa: 'GZCL プログラム計算ツール｜T1/T2/T3の重量を1RMから自動計算',
    seoTitleEn: 'GZCL Calculator — T1/T2/T3 weights auto-calculated from your 1RM',
    seoDescJa: '1RMからGZCLのT1・T2・T3全種目の重量を自動計算。スプレッドシートなしで4日間のプログラム全体を即生成。上級者向けストレングス法。',
    seoDescEn: 'Auto-calculate GZCL T1/T2/T3 weights from your 1RM. Generate the full 4-day program instantly without a spreadsheet.',
    descJa: 'T1/T2/T3の3層構造。高重量から高レップまで全域を網羅する上級者向けストレングス法。',
    descEn: 'Three-tier T1/T2/T3 structure covering heavy strength to high-rep work. A comprehensive approach for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '75–95%',
    relatedSlugs: ['wendler-531', 'nsuns-531', 'phat'],
    targetAudienceJa: '自分でプログラムを設計したい上級者。T1/T2/T3の構造を使ってカスタマイズしながら最高レベルの筋力を追求したい方。',
    targetAudienceEn: 'Advanced lifters who want to self-program using a flexible framework. Ideal for those who want to customize volume and intensity across T1/T2/T3 tiers.',
    faq: [
      {
        questionJa: 'GZCLメソッドは何週間のプログラムですか？',
        answerJa: 'GZCLはフレームワークであり、固定の期間はありません。一般的には12週を1ブロックとして計画し、T1・T2・T3の構成を変えながら長期的に継続します。',
        questionEn: 'How long is the GZCL program?',
        answerEn: 'GZCL is a framework rather than a fixed program. Most implementations plan 12-week blocks, cycling T1/T2/T3 exercise selections. It can be run indefinitely with periodic block changes.',
      },
      {
        questionJa: 'GZCLは初心者に向いていますか？',
        answerJa: '上級者向けです。T1/T2/T3の負荷管理と自己プログラミングの知識が必要なため、まずStrongLifts 5×5などで基礎を作ってから挑戦することを推奨します。',
        questionEn: 'Is GZCL for beginners?',
        answerEn: 'GZCL is designed for advanced lifters. Managing T1/T2/T3 load progression requires training experience and program literacy. Build your foundation with a beginner program first.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: '5/3/1はプレスクリプティブで週4日・各メイン種目に1日ずつ当てます。GZCLは柔軟なフレームワークで、T1（最重量・低レップ）をベースに補助種目の量を自由に設計できます。GZCLの方が上級者がカスタマイズできる余地が大きいです。',
        questionEn: 'How does GZCL differ from Wendler 5/3/1?',
        answerEn: '5/3/1 is prescriptive — 4 days per week, one main lift per session. GZCL is a flexible framework where you design T2 and T3 volume around heavy T1 work. GZCL offers more customization for experienced programmers.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '主要種目の1RMを入力すると、T1/T2/T3の各種目の重量が自動計算されます。スプレッドシートなしでGZCLの全4日プログラムを即座に確認できます。',
        questionEn: 'How do I use the GZCL calculator?',
        answerEn: 'Enter your 1RMs and generate — the calculator outputs T1, T2, and T3 weights across the full 4-day program. No spreadsheet needed to run the GZCL method.',
      },
      {
        questionJa: 'GZCLのT1・T2・T3とはどういう意味ですか？',
        answerJa: 'T1（Tier 1）はメイン種目の高強度・低レップセット（1RMの85〜90%で2〜5レップ）です。T2は同じ動作パターンの補助種目で中強度・中レップ（10レップ前後）、T3は軽重量・高レップ（15レップ以上）のアクセサリー種目です。この3層構造が筋力・筋量・持久力を同時に鍛えるGZCLの核心です。',
        questionEn: 'What do T1, T2, and T3 mean in the GZCL method?',
        answerEn: 'T1 (Tier 1) is your main barbell lift performed heavy — typically 85–90% 1RM for 2–5 reps. T2 is a supplemental lift for the same movement pattern at moderate intensity for around 10 reps. T3 covers light, high-rep accessory work at 15+ reps. This three-tier pyramid simultaneously develops strength, muscle size, and endurance.',
      },
      {
        questionJa: 'GZCLはバーベルなしでもできますか？',
        answerJa: 'GZCLはT1種目（スクワット・ベンチ・デッドリフト・ショルダープレス）にバーベルを使うことを前提に設計されています。T2・T3はダンベルやマシンで代替可能ですが、T1にバーベルがないと本来の効果は得られません。ダンベルのみの環境ならPPLやPHULのほうが器具の選択肢が広いためおすすめです。',
        questionEn: 'Can I do GZCL without a barbell?',
        answerEn: 'GZCL is built around barbell T1 lifts (squat, bench, deadlift, overhead press). T2 and T3 tiers can use dumbbells or machines, but removing the barbell from T1 undermines the core strength stimulus. If you only have dumbbells or machines, PPL or PHUL offer more equipment flexibility.',
      },
    ],
  },
  {
    slug: 'nsuns-531',
    nameJa: 'nSuns 5/3/1',
    nameEn: 'nSuns 5/3/1',
    seoTitleJa: 'nSuns 計算ツール｜nSuns 5/3/1の9セット重量を1RMから自動生成',
    seoTitleEn: 'nSuns Calculator — nSuns 5/3/1 weights for all 9 sets, auto-generated from 1RM',
    seoDescJa: '1RMからnSunsの全5日・各セットの重量を自動計算。T1の9セット+AMRAPをスプレッドシートなしで管理。高ボリューム5/3/1を手軽に実行。',
    seoDescEn: 'Auto-generate nSuns 5/3/1 weights for every set across all 5 days from your 1RM. Ditch the spreadsheet — get the full high-volume program instantly.',
    descJa: '5/3/1の高ボリューム派生版。週5日・1種目9セット以上の超高強度プログラム。',
    descEn: 'A high-volume 5/3/1 variant. 5 days/week with 9+ sets per main lift. For those who want maximum volume.',
    level: 'advanced',
    daysPerWeek: 5,
    category: 'strength',
    durationWeeks: 16,
    intensityRange: '70–95%',
    relatedSlugs: ['wendler-531', 'gzcl', 'smolov-jr'],
    targetAudienceJa: '5/3/1の経験があり、さらに高いボリュームに挑戦したい中〜上級者。週5日トレーニングできる十分な回復能力がある方。',
    targetAudienceEn: 'Intermediate-to-advanced lifters experienced with 5/3/1 who want to push volume higher. Requires 5 training days per week and strong recovery.',
    faq: [
      {
        questionJa: 'nSuns 5/3/1は何週間のプログラムですか？',
        answerJa: 'nSunsは16週（4ヶ月）を目安にする高ボリュームプログラムです。ただし固定の終了期間はなく、継続して回すことも可能です。',
        questionEn: 'How long is the nSuns 5/3/1 program?',
        answerEn: 'nSuns is typically run for 16 weeks (about 4 months) as a structured block, but has no mandatory end date. Some lifters run it for much longer with periodic deloads.',
      },
      {
        questionJa: 'nSunsはオリジナルの5/3/1より難しいですか？',
        answerJa: 'はい、大幅にボリュームが多いです。メイン種目1つあたり9セット以上、週5日のトレーニングが必要なため、回復能力が高い中〜上級者向けです。Wendler 5/3/1に慣れた後でnSunsへ移行するのが一般的な流れです。',
        questionEn: 'Is nSuns harder than regular Wendler 5/3/1?',
        answerEn: 'Yes — significantly more volume. nSuns requires 9+ sets per main lift across 5 training days per week. It suits intermediate-to-advanced lifters with good recovery capacity. A common path is to master Wendler 5/3/1 first, then graduate to nSuns.',
      },
      {
        questionJa: 'nSunsに初心者は向いていませんか？',
        answerJa: '向いていません。週5日・高ボリュームのプログラムは初心者には過剰であり、怪我のリスクが高まります。まずStrongLifts 5×5やStarting Strengthで半年〜1年のベースを作ることが重要です。',
        questionEn: 'Can beginners do nSuns?',
        answerEn: 'No. The 5-day high-volume structure is excessive for beginners and raises injury risk. Build a solid base with StrongLifts 5×5 or Starting Strength for 6–12 months before attempting nSuns.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力すると、nSunsの全5日間・各セット（T1の9セット含む）の重量が自動生成されます。AMRAPセットのターゲット重量も出力されます。',
        questionEn: 'How does the nSuns calculator work?',
        answerEn: 'Enter your 1RMs, generate, and get exact weights for every set across all 5 training days — including all 9 T1 sets and the AMRAP target. No spreadsheet required.',
      },
      {
        questionJa: 'nSuns 5/3/1の自動進捗はどう機能しますか？',
        answerJa: 'nSunsはAMRAPセットの実施レップ数に基づいてトレーニングマックス（TM）を動的に調整します。目標レップ数を超えればTMを増加し、未達なら現状維持または減少します。この自動調整がオリジナルWendler 5/3/1との最大の違いであり、実際のパフォーマンスに基づいてリアルタイムで重量を最適化します。',
        questionEn: 'How does nSuns auto-progression work?',
        answerEn: 'nSuns adjusts your Training Max based on the reps you actually hit on the AMRAP set — exceed the target and your TM goes up; fall short and it holds or drops. This performance-based auto-regulation is the key difference from standard Wendler 5/3/1, which uses fixed TM increases each cycle.',
      },
      {
        questionJa: 'nSunsはどのくらいの期間継続すべきですか？',
        answerJa: 'nSunsに固定の終了期間はありませんが、16週（約4ヶ月）を1ブロックとして計画するトレーニーが多いです。週5日・高ボリュームが継続するため、4〜6週ごとに1週間のディロードを挿入することが重要です。疲労が抜けなくなったら一時的にWendler 5/3/1など低ボリュームのプログラムに切り替えることも有効です。',
        questionEn: 'How long should I run nSuns 5/3/1?',
        answerEn: 'nSuns has no fixed end date, but most lifters plan 16-week (4-month) blocks. Because volume is very high across 5 training days, a deload week every 4–6 weeks is essential. If you consistently can\'t recover between sessions, temporarily drop to a lower-volume program like standard Wendler 5/3/1 before returning.',
      },
    ],
  },
  {
    slug: 'phul',
    nameJa: 'PHUL',
    nameEn: 'PHUL',
    seoTitleJa: 'PHUL プログラム作成｜パワー&肥大4分割を1RMから自動生成',
    seoTitleEn: 'PHUL Program Generator — Power & Hypertrophy Upper/Lower split from your 1RM',
    seoDescJa: '1RMからPHULの全4日・パワー日と肥大日の重量を自動計算。筋力と筋肥大を同時に狙う週4日分割プログラムを即生成。',
    seoDescEn: 'Build your PHUL (Power Hypertrophy Upper Lower) program from your 1RM. Power and hypertrophy day weights auto-calculated for all 4 days.',
    descJa: 'パワー日＋肥大日の4分割。筋力と筋肥大を最大化するバランスの取れた週4日プログラム。',
    descEn: 'Power + Hypertrophy Upper/Lower split. 4 days/week designed to maximize both strength and muscle size.',
    level: 'intermediate',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
    relatedSlugs: ['phat', 'ppl', 'gvt'],
    targetAudienceJa: '筋力と筋肥大の両方を狙いたい中級者。週4日でパワー日と肥大日を組み合わせたバランスの良いプログラムを求める方。',
    targetAudienceEn: 'Intermediate lifters who want both strength and size gains. PHUL\'s 4-day upper/lower split balances power days and hypertrophy days efficiently.',
    faq: [
      {
        questionJa: 'PHULは何週間のプログラムですか？',
        answerJa: '明確な終了期間はありませんが、一般的に8〜12週を1フェーズとして見直しながら継続します。',
        questionEn: 'How long is the PHUL program?',
        answerEn: 'PHUL does not have a fixed duration. Most lifters run 8–12 week phases, reviewing and adjusting exercise selection at the end of each block.',
      },
      {
        questionJa: 'PHULは初心者に向いていますか？',
        answerJa: '中級者向けです。パワー日（低レップ高重量）と肥大日（中〜高レップ）を使い分けるため、主要種目のフォームが固まっていることが必要です。初心者はまず3日間の全身プログラムから始めましょう。',
        questionEn: 'Is PHUL suitable for beginners?',
        answerEn: 'PHUL is intermediate-level. Cycling between power days (heavy low reps) and hypertrophy days (moderate high reps) requires solid technique on major lifts. Beginners should start with a full-body 3-day program.',
      },
      {
        questionJa: 'PHATとの違いは何ですか？',
        answerJa: 'PHULは週4日の上半身/下半身分割で筋力と筋肥大のバランスを取ります。PHATはLayne Nortonが考案した週5日のプログラムで、より高頻度かつ高ボリュームです。より多くの時間をジムに使えるならPHATが選択肢になります。',
        questionEn: 'How does PHUL differ from PHAT?',
        answerEn: 'PHUL is a 4-day upper/lower split balancing strength and hypertrophy. PHAT (by Layne Norton) is a 5-day program with more frequent power and hypertrophy days. Choose PHAT if you can commit to 5 days per week.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、PHULの全4日（上半身パワー・下半身パワー・上半身肥大・下半身肥大）の種目・重量が一括出力されます。',
        questionEn: 'How do I use the PHUL calculator?',
        answerEn: 'Enter your 1RMs and generate — you get all 4 days (Upper Power, Lower Power, Upper Hypertrophy, Lower Hypertrophy) with exercises and exact weights calculated for your level.',
      },
      {
        questionJa: 'PHULのパワー日と肥大日の重量の目安は？',
        answerJa: 'パワー日（Day 1・Day 2）はメイン種目を1RMの85〜90%で3〜5レップ行います。肥大日（Day 3・Day 4）は同じ種目を1RMの65〜70%で8〜12レップ行います。この重量差が神経系（パワー日）と筋肥大（肥大日）の両方を刺激するPHULの核心です。',
        questionEn: 'What weights should I use on PHUL power vs hypertrophy days?',
        answerEn: 'On power days (Days 1 & 2), use 85–90% of your 1RM for 3–5 reps on main lifts. On hypertrophy days (Days 3 & 4), drop to 65–70% of 1RM for 8–12 reps. This contrast between heavy strength work and moderate hypertrophy volume is the mechanism that drives both simultaneously.',
      },
      {
        questionJa: 'PHULはどのくらいの期間続けるのが理想ですか？',
        answerJa: 'PHULは固定の終了期間がなく継続的に回せるプログラムです。8〜12週を1フェーズとして見直しながら継続するのが一般的です。停滞した場合はSmolov JrやGVTなど短期特化ブロックを挟んでからPHULに戻る方法も効果的です。',
        questionEn: 'How long should I run the PHUL program?',
        answerEn: 'PHUL has no fixed end date — run it in 8–12 week phases, reassessing exercise selection at the end of each block. If you plateau, a short specialization block (Smolov Jr for the bench, GVT for hypertrophy volume) followed by a return to PHUL can reignite progress.',
      },
    ],
  },
  {
    slug: 'starting-strength',
    nameJa: 'Starting Strength',
    nameEn: 'Starting Strength',
    seoTitleJa: 'Starting Strength 計算ツール｜開始重量とA/Bワークアウトを1RMから生成',
    seoTitleEn: 'Starting Strength Calculator — Starting weights and A/B workouts from your 1RM',
    seoDescJa: '1RMからStarting Strengthの開始重量を自動計算。スクワット・ベンチ・デッドリフト・パワークリーンの初回重量を即座に確認。Rippetoe式初心者プログラム。',
    seoDescEn: 'Get your Starting Strength starting weights from your 1RM. Squat, bench, deadlift, and power clean — know exactly where to begin.',
    descJa: 'Mark Rippetoe考案の初心者向け線形プログレッション。3×5のシンプルさで確実に伸びる。',
    descEn: "Mark Rippetoe's beginner linear progression. Simple 3×5 structure — reliable, proven strength gains.",
    level: 'beginner',
    daysPerWeek: 3,
    category: 'beginner',
    durationWeeks: 10,
    intensityRange: '60–80%',
    relatedSlugs: ['stronglifts-5x5', 'texas-method', 'wendler-531'],
    targetAudienceJa: 'バーベルトレーニングを初めて行う完全な初心者。スクワット・デッドリフト・ベンチプレスのフォームを習得しながら確実に力をつけたい方。',
    targetAudienceEn: 'Complete beginners to barbell training. Starting Strength teaches squat, deadlift, bench press, and press technique while building strength through linear progression.',
    faq: [
      {
        questionJa: 'Starting Strengthは何週間のプログラムですか？',
        answerJa: '一般的に10〜16週が目安ですが、線形プログレッションが続く限り延長可能です。週3回・3×5のシンプルな構成で、重量が上がり続けることが唯一の進捗指標です。',
        questionEn: 'How long is Starting Strength?',
        answerEn: 'Typically 10–16 weeks, but you can continue as long as you keep adding weight each session. The 3-day-per-week, 3×5 structure is simple enough to run until linear progression stalls.',
      },
      {
        questionJa: 'Starting StrengthとStrongLifts 5×5はどちらが初心者に向いていますか？',
        answerJa: 'どちらも優れた初心者プログラムです。Starting Strengthは3×5でデッドリフト・パワークリーンを重視し、書籍の指導内容が詳しい。StrongLiftsは5×5でアプリ管理が楽。指導者なしで独学するならStrongLiftsが取り組みやすい傾向があります。',
        questionEn: 'Starting Strength vs StrongLifts 5×5 — which is better for beginners?',
        answerEn: 'Both are excellent. Starting Strength uses 3×5 and emphasizes deadlifts and power cleans with detailed coaching in the book. StrongLifts uses 5×5 and has an easy-to-use app. For self-taught beginners, StrongLifts is often easier to start.',
      },
      {
        questionJa: '女性でもStarting Strengthはできますか？',
        answerJa: 'はい、性別に関係なく有効なプログラムです。開始重量をフォーム習得に適した軽い重量から設定し、毎セッション着実に積み上げていきます。女性でも同じ原理で筋力が伸びます。',
        questionEn: 'Can women do Starting Strength?',
        answerEn: 'Yes, absolutely. Starting Strength is effective regardless of gender. Women start at a manageable weight to learn the movement patterns and progress from there — the linear progression principle works the same way.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '現在の1RMを入力するか、初回の場合はすべて0のまま生成ボタンを押してください。スクワット・ベンチ・デッドリフト・プレスの開始重量とA/Bワークアウトが自動生成されます。',
        questionEn: 'How does the Starting Strength calculator work?',
        answerEn: 'Enter your current 1RMs, or leave them at zero for your very first session. The calculator generates starting weights and your Workout A / Workout B schedule — ready to use on day one.',
      },
      {
        questionJa: 'Starting Strengthのパワークリーンはダンベルロウで代替できますか？',
        answerJa: 'はい、バーベルのパワークリーンが難しい場合はダンベルロウやラットプルダウンで代替できます。ただしMark Rippetoeはパワークリーンに爆発的な動作として独自の価値があるとしており、バーベル環境があれば本来の種目を推奨しています。初心者のうちは正しいフォームの習得が最優先です。',
        questionEn: 'Can I substitute dumbbell rows for power cleans in Starting Strength?',
        answerEn: 'Yes — dumbbell rows or lat pulldowns are accepted substitutes when the Olympic lift is unavailable or not yet learned. Rippetoe notes the power clean has unique explosive value no row can fully replicate, but substituting confidently is far better than skipping back work entirely.',
      },
      {
        questionJa: 'Starting Strengthの後はどのプログラムに移行すべきですか？',
        answerJa: '線形プログレッションが繰り返し停滞したら、Texas MethodやWendler 5/3/1への移行が一般的です。Starting Strengthで得た基礎筋力を土台に、より長いプログレッションサイクルで継続的な筋力向上を図りましょう。多くのトレーニーが6〜12ヶ月のStarting Strength期間を経て移行します。',
        questionEn: 'What program should I move to after Starting Strength?',
        answerEn: 'When linear progression stalls repeatedly, Texas Method or Wendler 5/3/1 are the natural next steps. Both extend progression to weekly or monthly cycles, building on the strength base Starting Strength created. Most lifters make the switch after 6–12 months on the program.',
      },
    ],
  },
  {
    slug: 'gvt',
    nameJa: 'German Volume Training（GVT）',
    nameEn: 'German Volume Training (GVT)',
    seoTitleJa: 'GVT 計算ツール｜German Volume Training 10×10の重量を1RMから自動計算',
    seoTitleEn: 'GVT Calculator — German Volume Training 10×10 weights from your 1RM',
    seoDescJa: '1RMからGVT（ジャーマン・ボリューム・トレーニング）の10×10重量を自動計算。6週間・全24セッションの重量を即生成。最大筋肥大を狙う上級者向け。',
    seoDescEn: 'Auto-calculate German Volume Training (GVT) 10×10 weights from your 1RM. Generate the full 6-week, 24-session program instantly.',
    descJa: '10×10の超高ボリューム筋肥大プログラム。6週間で最大の筋量増加を狙う上級者向け。',
    descEn: '10×10 extreme volume hypertrophy program. 6-week cycles designed to maximize muscle growth for advanced lifters.',
    level: 'advanced',
    daysPerWeek: 4,
    category: 'hypertrophy',
    durationWeeks: 6,
    intensityRange: '60–70%',
    relatedSlugs: ['ppl', 'phul', 'phat'],
    targetAudienceJa: '筋肥大を最優先とする上級者。高ボリューム刺激で停滞を打ち破りたい、または体型の大きな変化を6週間で求める方。',
    targetAudienceEn: 'Advanced lifters who prioritize maximum hypertrophy. GVT breaks through plateaus with extreme volume and can produce significant size changes in 6 weeks.',
    faq: [
      {
        questionJa: 'GVT（ジャーマン・ボリューム・トレーニング）は何週間ですか？',
        answerJa: '標準的なGVTは6週間です。10×10という極めて高いボリュームで筋肥大を狙います。6週後は休養を挟んでから次のブロックに進むことを推奨します。',
        questionEn: 'How long is German Volume Training (GVT)?',
        answerEn: 'Standard GVT is 6 weeks. The extreme 10×10 volume is designed to maximize hypertrophy in a concentrated block. After 6 weeks, a recovery period is strongly recommended before the next block.',
      },
      {
        questionJa: 'GVTは初心者でも大丈夫ですか？',
        answerJa: '上級者向けです。10×10の超高ボリュームは初心者の回復能力を超えており、怪我やオーバートレーニングのリスクがあります。少なくとも1〜2年のトレーニング歴があることが推奨されます。',
        questionEn: 'Is GVT suitable for beginners?',
        answerEn: 'No — GVT is for advanced lifters. The 10×10 volume exceeds a beginner\'s recovery capacity and carries serious overtraining risk. At minimum 1–2 years of consistent training are recommended.',
      },
      {
        questionJa: 'PPLとGVTはどちらが筋肥大に効果的ですか？',
        answerJa: 'GVTは短期的な筋肥大刺激において非常に強力ですが、6週の集中ブロックです。PPLは週6日の継続的なトレーニングで長期的な筋量増加に適しています。短期集中で体型を変えたいならGVT、持続的な筋量増加ならPPLが向いています。',
        questionEn: 'GVT vs PPL — which is better for hypertrophy?',
        answerEn: 'GVT delivers an intense hypertrophy stimulus in a focused 6-week block. PPL provides sustained hypertrophy volume across 6 days per week for long-term muscle building. Use GVT for a short-term shock block; use PPL for ongoing volume.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '1RMを入力して生成すると、GVTの6週間・全24セッションの10×10重量が自動計算されます。1RMの60〜70%が作業重量の目安です。',
        questionEn: 'How does the GVT calculator work?',
        answerEn: 'Enter your 1RM and generate. The calculator outputs 10×10 working weights for the full 6-week, 24-session program. Working weights are typically set at 60–70% of your 1RM.',
      },
      {
        questionJa: 'GVTの10×10が達成できない場合はどうすれば？',
        answerJa: '最初から全セットで10レップ達成するのが難しいのは正常です。できなかったレップ数を記録しておき、全セットで10レップ達成できるようになったら重量を2.5〜5%増やします。セット間のインターバルは厳密に60秒を守ることがGVTの累積疲労の鍵です。最初は「物足りない」と感じる重量から始めてください。',
        questionEn: 'What should I do if I can\'t complete all 10×10 sets in GVT?',
        answerEn: 'Struggling to hit all 10×10 in early sessions is completely normal. Log your actual reps and only increase the weight once you\'ve successfully completed 10 reps across all 10 sets. Keeping a strict 60-second rest interval is essential — that cumulative fatigue is what drives the hypertrophy response. Start lighter than you think you need to.',
      },
      {
        questionJa: 'GVTが終わった後のおすすめプログラムは？',
        answerJa: '6週間のGVTブロック後は1週間のディロードを必ず取ります。次のプログラムは目標によって選択しましょう。筋力向上ならWendler 5/3/1やGZCL、さらなる筋肥大ならPPLやPHULへの移行がおすすめです。GVTで得た筋量を「使える筋力」に変換するため、低レップ・高強度の期間を続けるのも効果的なアプローチです。',
        questionEn: 'What program should I do after GVT?',
        answerEn: 'After a 6-week GVT block, take a mandatory 1-week deload, then choose your next phase by goal. For strength, move to Wendler 5/3/1 or GZCL to convert new muscle into usable strength. For continued hypertrophy, PPL or PHUL maintain high volume with more exercise variety. Alternating GVT blocks with strength-focused programs is a proven long-term strategy.',
      },
    ],
  },
  {
    slug: 'texas-method',
    nameJa: 'Texas Method',
    nameEn: 'Texas Method',
    seoTitleJa: 'Texas Method 計算ツール｜Volume/Recovery/Intensity日の重量を1RMから生成',
    seoTitleEn: 'Texas Method Calculator — Volume, Recovery, and Intensity day weights from your 1RM',
    seoDescJa: '1RMからTexas Methodの3日サイクル全種目の重量を自動計算。Volume Day・Recovery Day・Intensity Day（PR日）の重量を一括生成。毎週自己ベストを更新する中級者プログラム。',
    seoDescEn: 'Auto-calculate Texas Method weights for all three days — Volume, Recovery, and Intensity (PR day) — from your 1RM. Set a new PR every week.',
    descJa: '週3日・Volume/Recovery/Intensityの3日サイクル。毎週PRを更新する中級者向け。',
    descEn: '3-day Volume/Recovery/Intensity cycle. Set a new PR every week as an intermediate lifter.',
    level: 'intermediate',
    daysPerWeek: 3,
    category: 'strength',
    durationWeeks: 12,
    intensityRange: '70–90%',
    relatedSlugs: ['wendler-531', 'starting-strength', 'stronglifts-5x5'],
    targetAudienceJa: 'StrongLiftsやStarting Strengthを卒業したばかりの中級者。毎週のPR更新を目標に、ボリュームと強度をバランスよく積み上げたい方。',
    targetAudienceEn: 'Intermediate lifters who have graduated from beginner programs and want to set a new PR every week through a structured Volume-Recovery-Intensity cycle.',
    faq: [
      {
        questionJa: 'Texas Methodは何週間のプログラムですか？',
        answerJa: 'Texas Methodは12週を目安にしますが、毎週PRを更新し続ける限り期間の制限はありません。Volume Day・Recovery Day・Intensity Day（PR日）の3日サイクルが続きます。',
        questionEn: 'How long is the Texas Method?',
        answerEn: 'Texas Method has no fixed duration — 12 weeks is a common first block, but the program continues as long as you can hit new PRs on Intensity Day. The 3-day weekly cycle repeats indefinitely.',
      },
      {
        questionJa: 'Texas Methodはどんな人に向いていますか？',
        answerJa: 'StrongLiftsやStarting Strengthを卒業した中級者に最適です。毎週のPRを目標に、Volume DayでボリュームをこなしてIntensity DayでPRに挑む設計です。',
        questionEn: 'Who is the Texas Method for?',
        answerEn: 'Texas Method is ideal for intermediate lifters who have graduated from StrongLifts or Starting Strength. The weekly Volume-Recovery-Intensity cycle allows you to set a new PR every single week.',
      },
      {
        questionJa: 'Wendler 5/3/1との違いは何ですか？',
        answerJa: 'Texas Methodは週1回のPRを目標にした短期サイクルです。5/3/1は4週サイクルで、最終セットのAMRAPが主な進捗指標です。Texas Methodの方がPR頻度が高く強度重視。5/3/1はボリュームと強度のバランスが取れています。',
        questionEn: 'What is the difference between Texas Method and Wendler 5/3/1?',
        answerEn: 'Texas Method aims for a PR every week using a Volume-Recovery-Intensity 3-day cycle. Wendler 5/3/1 runs 4-week cycles with AMRAPs as the progress marker. Texas Method has a higher PR frequency; 5/3/1 balances volume and intensity across a longer cycle.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力すると、Texas Methodの3日間（ボリューム・回復・インテンシティ）全種目の重量が自動計算されます。Intensity Dayの目標重量もすぐに確認できます。',
        questionEn: 'How do I use the Texas Method calculator?',
        answerEn: 'Enter your 1RMs and generate. The calculator outputs all weights for Volume Day, Recovery Day, and Intensity Day across all main lifts — including your weekly PR target.',
      },
      {
        questionJa: 'Texas Methodで停滞したときの対処法は？',
        answerJa: 'Intensity DayのPRが3週連続で更新できない場合は停滞です。まずVolume Dayの重量を5〜10%落としてリセットするのが最初の対処法です。それでも進まない場合はWendler 5/3/1など4週サイクルのプログラムへの移行を検討しましょう。',
        questionEn: 'How do I handle stalls in Texas Method?',
        answerEn: 'If you can\'t set a new Intensity Day PR for 3 weeks in a row, the program has stalled. First response: drop Volume Day weights by 5–10% and work back up. If that fails, you may have outgrown Texas Method and need to move to a longer-cycle program like Wendler 5/3/1.',
      },
      {
        questionJa: 'Texas MethodはStarting Strengthの後に始めるのが一般的ですか？',
        answerJa: 'はい、Texas MethodはStarting StrengthやStrongLifts 5×5で線形プログレッションが止まったタイミングで移行する中級者プログラムとして非常に一般的です。週1回のPR更新という明確な目標が多くのトレーニーにとって大きなモチベーションになります。',
        questionEn: 'Is Texas Method typically done after Starting Strength?',
        answerEn: 'Yes — Texas Method is one of the most popular transitions out of beginner linear progression programs like Starting Strength or StrongLifts 5×5. The weekly PR target gives a clear performance goal each week, which many lifters find highly motivating compared to programs where progress is measured over months.',
      },
    ],
  },
  {
    slug: 'phat',
    nameJa: 'PHAT',
    nameEn: 'PHAT',
    seoTitleJa: 'PHAT プログラム作成｜Layne Norton式5日分割を1RMから自動生成',
    seoTitleEn: 'PHAT Program Generator — Layne Norton\'s 5-day split from your 1RM',
    seoDescJa: '1RMからPHAT（Power Hypertrophy Adaptive Training）の全5日・パワーデイと肥大デイの重量を自動計算。Layne Norton考案の高頻度プログラムをすぐ実行。',
    seoDescEn: 'Generate Layne Norton\'s PHAT (Power Hypertrophy Adaptive Training) program from your 1RM. Power and hypertrophy day weights auto-calculated across all 5 days.',
    descJa: 'Layne Norton考案の週5日高頻度プログラム。パワーと肥大を両立するアダプティブな設計。',
    descEn: "Layne Norton's 5-day high-frequency program. Adaptive training that bridges powerlifting and bodybuilding.",
    level: 'advanced',
    daysPerWeek: 5,
    category: 'hypertrophy',
    durationWeeks: 8,
    intensityRange: '65–85%',
    relatedSlugs: ['phul', 'gzcl', 'ppl'],
    targetAudienceJa: 'パワーリフティングとボディビルディングの両方に関心がある上級者。週5日トレーニングでき、筋力と筋量の両立を追求したい方。',
    targetAudienceEn: 'Advanced lifters interested in both powerlifting and bodybuilding. PHAT combines power and hypertrophy training across 5 days per week for dual adaptation.',
    faq: [
      {
        questionJa: 'PHATは何週間のプログラムですか？',
        answerJa: '明確な終了期間はありませんが、8〜12週を1フェーズとして見直しながら継続するのが一般的です。週5日のトレーニングが必要なため、スケジュール管理が重要です。',
        questionEn: 'How long is the PHAT program?',
        answerEn: 'PHAT has no fixed end date. Most lifters run 8–12 week phases, reassessing exercise selection and loads at the end of each block. The 5-day schedule requires good recovery management.',
      },
      {
        questionJa: 'PHATはパワーリフティングとボディビルディングのどちらに向いていますか？',
        answerJa: '両方です。PHATの設計思想はパワー（低レップ高重量）と肥大（中〜高レップ高ボリューム）を同週内で組み合わせることです。Layne Norton自身がパワーリフターとボディビルダーの両面を持つことから生まれたプログラムです。',
        questionEn: 'Is PHAT for powerlifting or bodybuilding?',
        answerEn: 'Both. PHAT bridges powerlifting and bodybuilding by combining power days (low reps, heavy loads) with hypertrophy days (moderate-high reps, high volume) in the same week. It was created by Layne Norton who competes in both disciplines.',
      },
      {
        questionJa: 'PHULとの違いは何ですか？',
        answerJa: 'PHULは週4日、PHATは週5日です。PHATの方がトレーニング頻度が高く、ボリュームも多いため、より高い回復能力が必要です。PHULが忙しいトレーニーに向くのに対し、PHATは週5日ジムに行ける上級者に向いています。',
        questionEn: 'How does PHAT compare to PHUL?',
        answerEn: 'PHUL is 4 days per week; PHAT is 5 days. PHAT has higher frequency and volume, demanding superior recovery. PHUL suits lifters with busy schedules; PHAT is for advanced athletes who can commit to 5 gym days weekly.',
      },
      {
        questionJa: 'この計算機はどう使いますか？',
        answerJa: '各種目の1RMを入力して生成ボタンを押すと、PHATの全5日（パワーデイ2日+肥大デイ3日）の種目と重量が自動出力されます。',
        questionEn: 'How do I use the PHAT calculator?',
        answerEn: 'Enter your 1RMs and generate. The calculator outputs all exercises and weights for the full 5-day PHAT split — 2 power days and 3 hypertrophy days — auto-calculated from your strength levels.',
      },
      {
        questionJa: 'PHATのスピードセットとはどういうものですか？',
        answerJa: 'PHATの肥大日（Day 3〜5）では、各種目の最初のセットを「スピードセット」として実施します。1RMの60〜65%程度の重量で6レップを爆発的に素早く行い、その後通常の肥大セット（8〜12レップ）に移行します。パワー日で刺激した神経系の適応を肥大日でも維持するための重要な要素です。',
        questionEn: 'What are speed sets in PHAT?',
        answerEn: 'On PHAT hypertrophy days (Days 3–5), each exercise begins with a speed set — typically 60–65% of 1RM for 6 reps performed explosively. After the speed set, you proceed with normal hypertrophy volume (8–12 reps). Speed sets maintain the neural drive developed on power days, keeping hypertrophy training connected to strength adaptations.',
      },
      {
        questionJa: 'PHATはPHULより難しいですか？',
        answerJa: 'PHATは週5日・より高頻度のプログラムのためPHULより回復への要求が高くなります。PHULは週4日でパワーと肥大をバランスよく組み合わせた設計です。PHATはパワーリフティングとボディビルディングの両方を追求したい上級者向けで、週5日ジムに通える時間と回復能力が必要です。',
        questionEn: 'Is PHAT harder than PHUL?',
        answerEn: 'PHAT is more demanding than PHUL due to its higher weekly frequency (5 vs 4 days) and greater total volume. PHUL suits lifters who want a balanced strength-and-size program with slightly less commitment. PHAT is for advanced athletes who can commit to 5 sessions per week and want to push both powerlifting and bodybuilding adaptations simultaneously.',
      },
    ],
  },
];

export function getProgram(slug: string, input: GeneratorInput): GeneratedProgram | null {
  const fn = programRegistry[slug];
  if (!fn) return null;
  return fn(input);
}

export type { ProgramMeta, GeneratedProgram, GeneratorInput };
